### ISSUE TITLE
Connect error = dial tcp XX.XX.XX.XX:65501: i/o timeout

### ISSUE THREAD

**Issue by Eludendil** [docker-slim/docker-slim#107]
Hello, cannot find out why I get this error. 
Docker-slim is working fine on my local laptop. 
Some context:

I am trying to use docker-slim inside my CI (using Gitlab). No error while running docker build but when i use `docker-slim build` i get a time out. Any idea why ?

**Comment by kcq** [comment]
@Eludendil what's the full `docker-slim build` command? In a Gitlab CI environment it's probably better to use the Dockerized version of `docker-slim`. 

Here's an example: `docker run -e DOCKER_HOST=tcp://$(grep docker /etc/hosts | cut -f1):2375 dslim/docker-slim build your-docker-image-name`

Note that with the `docker-slim` container you need to set the DOCKER_HOST variable for it using the Docker host IP address (that's what that `grep` and `cut` commands are doing in the example).

**Comment by Eludendil** [comment]
Thanks it fixed my issue. Was not setting the right DOCKER_HOST var.
