### ISSUE TITLE
need --no-http-probe or --http-probe needs to take "false" (or whatever)

### ISSUE THREAD

**Issue by TJM** [docker-slim/docker-slim#108]
Now (since at least 1.26.1), the `--http-probe` appears to be enabled by default, so you should probably have a `--no-http-probe` or allow `--http-probe false` to allow slimming non http containers (command line utilities)

WORKAROUND: `export DSLIM_HTTP_PROBE=false`

Thanks,
Tommy

**Comment by TJM** [comment]
I am dumb, it should be `--http-probe=false` not "(space)" ... canceling

**Comment by kcq** [comment]
yes, setting it to false should do the trick... here's a full example: `docker-slim build --http-probe=false my/golang-app` (from the golang [example](https://github.com/docker-slim/examples/blob/master/golang_standard/slim.command) ).

**Comment by TJM** [comment]
My problem was that I used the `--http-probe false` ... which *should* work in my opinion, but apparently the parameters are not parsed in the way I expected.
