### ISSUE TITLE
ToC Is Outdated

### ISSUE THREAD

**Issue by umutphp** [docker-slim/docker-slim#113]
The table of contents in the README file is outdated. There are also broken links like "NOTES" and "RECENT UPDATES".

**Comment by kcq** [comment]
Good catch :) Thanks for the note @umutphp !

**Comment by kcq** [comment]
refreshed the README TOC

**Comment by kcq** [comment]
reopen this ticket if/when something is broken :)

**Comment by umutphp** [comment]
@kcq Many thanks for the quick response and action. Just checked and README is ok now :).

PS: I am using [WOSPM/checker](https://github.com/WOSPM/checker) tool (which is a humble project of mine :)) to check your README. I was using docker-slim/docker-slim as one of the test repositories during my implementation. That's is how I found the 404s in your README.

**Comment by umutphp** [comment]
@kcq 
I am sorry but one more broken link exists in the README. The link **dockerhackday** in section [origins](https://github.com/docker-slim/docker-slim#origins) section is not valid anymore.

**Comment by kcq** [comment]
can't really do much about it... Docker got rid of that page... removed the link to reduce the confusion
