### ISSUE TITLE
Does docker-slim construct the seccomp profile by static analysis of the code?

### ISSUE THREAD

**Issue by QWERTY92009** [docker-slim/docker-slim#133]
The resulting seccomp profile would allow all system calls inherent to the code. It would be desirable to only allow system calls actually needed (observed in operation). Thanks for your help!

**Comment by kcq** [comment]
@QWERTY92009 The seccomp profile is built based on the information collected at runtime. It's not doing any static syscall analysis at this point in time though it'll be a nice enhancement in the future to cross reference the dynamic and static syscall information.
