### ISSUE TITLE
http-probe failure continues building

### ISSUE THREAD

**Issue by rcomanne** [docker-slim/docker-slim#139]
Hi, I've been playing around with docker-slim for a couple of days now.
When I run a docker-slim and check it with my own or the default http-probers after the build, I can see that the probes fail 5 times. After which it stops probing and continues the build.
There are some entries in the log of docker-slim telling me the probes failed, but other than that I did not find anything else indicating the slimmed container does NOT work.
Now I was wondering, is this the desired flow for this?

**Comment by otaconix** [comment]
I ran into the same issue. I thought everything was fine, until I tried running a container using the slimmed-down image, which ended up **very** small indeed, because not one probe got through.

Although docker-slim outputs a summary of the probe results, it just continues doing its thing regardless of these results. I don't want to presume to speak for @rcomanne, but I it'd be nice if we could tell docker-slim to fail if any probes fail.

**Comment by kcq** [comment]
@otaconix good idea to have a flag to stop if the http probes fail (simple enough to add though it might also be good to provide a chance to interact with the container out of band first before actually failing completely)

**Comment by kcq** [comment]
@rcomanne can you share a bit of background about your container image? What's in your image?  Is it an application/service or is it a generic image with a bunch of stuff in it, which you use to build other container images? If it's an application image what app stack are you using? What kind of application is it? Is it a web service or a web server? What network ports is it listening on? I'd love to repro your condition and this info will be super helpful!

**Comment by kcq** [comment]
@otaconix i'm also curious to learn more about your container image too. Is it a closed source / private project? What can you share? Speaking of sharing... is it possible for you to share to console output and do you mind enabling the debugging mode (using the global `--debug` flag) and enabling the container logs (using the `--show-clogs` flag)?

**Comment by otaconix** [comment]
@kcq What constitutes a probe failure though? Is that a non-2xx status code? Or errors on a lower level (TCP or lower)?

I'm not sure what a generic solution looks like. Maybe allowing the execution of some provided binary/script to be run as a probe would prove to be generic enough. Such a script would need to be invoked with the container ID or somesuch to enable it to figure out how to do what it needs to do. Then, the interface can be unambiguous: container ID goes in, exit code goes out. A non-zero exit code signals failure, and zero indicates success.

I'm just thinking out loud here. Maybe there's a simpler way to do this that's good enough.

**Comment by otaconix** [comment]
Mine was an nginx image with invalid configuration. I believe the container wasn't even running when the probes started.

**Comment by rcomanne** [comment]
> @rcomanne can you share a bit of background about your container image? What's in your image? Is it an application/service or is it a generic image with a bunch of stuff in it, which you use to build other container images? If it's an application image what app stack are you using? What kind of application is it? Is it a web service or a web server? What network ports is it listening on? I'd love to repro your condition and this info will be super helpful!

My Image was a Clair image, but what kind of image it is should not really matter. If I have a container which contains a webserver which can be checked by HTTP health checks, I'd expect the run to fail if the probes failed as well.
Like @otaconix said, just giving a non zero exit code would already be really helpful.

**Comment by kcq** [comment]
@rcomanne The new `--http-probe-exit-on-failure` flag will provide the behavior you are looking for (it's already there and it'll be available in the next release next week).

The reason I asked about the image is because I wanted to repro the condition and figure out how to make it not fail in the first place :-) Curious if you created your own Clair image or if you used an existing image ( https://quay.io/repository/coreos/clair or https://hub.docker.com/r/opensuse/clair , for example )

**Comment by rcomanne** [comment]
@kcq great, but is there a reason this is not default behaviour? Normally I'd expect a fail if there are failed probes default.

I used the coreos clair image for my testing.

**Comment by kcq** [comment]
@otaconix network failures are considered to be errors (so if the target HTTP API returned a 404 or another non-200 status it would be considered a successful call).

What kind of invalid nginx config did you have?

**Comment by otaconix** [comment]
@kcq You can reproduce it with an nginx image as follows (what causes the nginx configuration to be invalid seems irrelevant to me):

```
docker-slim build --http-probe-retry-count 1 --mount /dev/null:/etc/nginx/nginx.conf nginx:stable-alpine
```

**Comment by otaconix** [comment]
Here's the logging from a run of docker-slim with the above command (+ `--debug` and `--show-clogs`): https://gist.github.com/otaconix/659f79c43c965b84a60b04439b02002b

**Comment by kcq** [comment]
@otaconix Thanks for the repro info and the logs! Super useful! One potential feature to add is an application termination/crash detection, so it can be used as a data point figuring out the optimization command state/success though it might be tricky in some cases (need to investigate further)...

**Comment by rcomanne** [comment]
@kcq for full information, here is the logging of my run of the Clair image. There is no PostgreSQL connection information in the image, so Clair fails to start, so the container crashes.
As the container is not up, I do not expect any response from the webserver, so no 4xx or 5xx codes either, which should mean the build fails imo.
```
docker-slim build --dockerfile=Dockerfile . --include-exe=xz --include-exe=rpm --include-exe=git --show-clogs --http-probe=false --http-probe-cmd=GET:/health --http-probe-ports=6061 --tag=clair
docker-slim[build]: state=started
docker-slim[build]: info=params context=./file=Dockerfile continue.mode=probe rt.as.user=true keep.perms=true
docker-slim[build]: state=building message='building basic image'
docker-slim[build]: info=basic.image.name value=clair.fat
docker-slim[build]: state=basic.image.build.completed
docker-slim[build]: state=image.inspection.start
docker-slim[build]: info=image id=sha256:987b8f01b40da6e628439d3c4dadbb0062bae4eee055d554517692122838f56c size.bytes=452263354 size.human=452 MB
docker-slim[build]: info=image.users exe='kwxbuild' all='kwxbuild'
docker-slim[build]: info=image.stack index=0 name='quay.io/coreos/clair:v2.1.2' id='sha256:79be45f1fd930c266a21f360d45aec9202ccc9167c5e8b2ed0fd38c6ae79a583'
docker-slim[build]: info=image.stack index=1 name='clair.fat:latest' id='sha256:987b8f01b40da6e628439d3c4dadbb0062bae4eee055d554517692122838f56c'
docker-slim[build]: info=image.exposed_ports list='6060 6061'
docker-slim[build]: state=image.inspection.done
docker-slim[build]: state=container.inspection.start
docker-slim[build]: info=container status=created name=dockerslimk_38389_20200323090057 id=d90d1a3ac18f7efda59cdb0778cc22ed476b4ca65bd4fcdd3da95a71a2ba2748
docker-slim[build]: info=cmd.startmonitor status=sent
docker-slim[build]: info=event.startmonitor.done status=received
docker-slim[build]: info=container name=dockerslimk_38389_20200323090057 id=d90d1a3ac18f7efda59cdb0778cc22ed476b4ca65bd4fcdd3da95a71a2ba2748 target.port.list=[32818,32819] target.port.info=[6061/tcp => 0.0.0.0:32818,6060/tcp => 0.0.0.0:32819] message='YOU CAN USE THESE PORTS TO INTERACT WITH THE CONTAINER'
docker-slim[build]: state=http.probe.starting message='WAIT FOR HTTP PROBE TO FINISH'
docker-slim[build]: info=continue.after mode=probe message='no input required, execution will resume when HTTP probing is completed'
docker-slim[build]: info=prompt message='waiting for the HTTP probe to finish'
docker-slim[build]: state=http.probe.running
docker-slim[build]: info=http.probe.ports count=1 targets='32818'
docker-slim[build]: info=http.probe.commands count=1 commands='GET /health'
docker-slim[build]: info=http.probe.call status=error method=GET target=http://127.0.0.1:32818/health attempt=1 error='Get "http://127.0.0.1:32818/health": EOF' time=2020-03-23T09:01:15Z
docker-slim[build]: info=http.probe.call status=error method=GET target=http://127.0.0.1:32818/health attempt=2 error='Get "http://127.0.0.1:32818/health": EOF' time=2020-03-23T09:01:31Z
docker-slim[build]: info=http.probe.call status=error method=GET target=http://127.0.0.1:32818/health attempt=3 error='Get "http://127.0.0.1:32818/health": EOF' time=2020-03-23T09:01:47Z
docker-slim[build]: info=http.probe.call status=error method=GET target=http://127.0.0.1:32818/health attempt=4 error='Get "http://127.0.0.1:32818/health": EOF' time=2020-03-23T09:02:03Z
docker-slim[build]: info=http.probe.call status=error method=GET target=http://127.0.0.1:32818/health attempt=5 error='Get "http://127.0.0.1:32818/health": EOF' time=2020-03-23T09:02:19Z
docker-slim[build]: info=http.probe.summary total=5 failures=5 successful=0
docker-slim[build]: state=http.probe.done warning=no.successful.calls
docker-slim[build]: info=event message='HTTP probe is done'
docker-slim[build]: state=container.inspection.finishing
docker-slim: container stdout:
{"Event":"pgsql: no database connection string specified","Level":"fatal","Location":"main.go:97","Time":"2020-03-23 09:01:03.284763"}
cloning dir path = fsutil.dirInfo{src:"/usr", dst:"/opt/dockerslim/artifacts/files/usr", perms:0x800001ed, sys:fsutil.SysStat{Ok:true, Uid:0x0, Gid:0x0, Atime:syscall.Timespec{Sec:1584950048, Nsec:284210000}, Mtime:syscall.Timespec{Sec:1575904987, Nsec:0}, Ctime:syscall.Timespec{Sec:1584950048, Nsec:271210000}}}
cloning dir path = fsutil.dirInfo{src:"/usr/bin", dst:"/opt/dockerslim/artifacts/files/usr/bin", perms:0x800001ed, sys:fsutil.SysStat{Ok:true, Uid:0x0, Gid:0x0, Atime:syscall.Timespec{Sec:1584950048, Nsec:284210000}, Mtime:syscall.Timespec{Sec:1575904988, Nsec:0}, Ctime:syscall.Timespec{Sec:1584950048, Nsec:271210000}}}
cloning dir path = fsutil.dirInfo{src:"/lib", dst:"/opt/dockerslim/artifacts/files/lib", perms:0x800001ed, sys:fsutil.SysStat{Ok:true, Uid:0x0, Gid:0x0, Atime:syscall.Timespec{Sec:1584950048, Nsec:277210000}, Mtime:syscall.Timespec{Sec:1575904988, Nsec:0}, Ctime:syscall.Timespec{Sec:1584950048, Nsec:270210000}}}
cloning dir path = fsutil.dirInfo{src:"/etc", dst:"/opt/dockerslim/artifacts/files/etc", perms:0x800001ed, sys:fsutil.SysStat{Ok:true, Uid:0x0, Gid:0x0, Atime:syscall.Timespec{Sec:1584953801, Nsec:381117000}, Mtime:syscall.Timespec{Sec:1584954057, Nsec:759185000}, Ctime:syscall.Timespec{Sec:1584954057, Nsec:759185000}}}
cloning dir path = fsutil.dirInfo{src:"/etc/clair", dst:"/opt/dockerslim/artifacts/files/etc/clair", perms:0x800001ed, sys:fsutil.SysStat{Ok:true, Uid:0x0, Gid:0x0, Atime:syscall.Timespec{Sec:1584953801, Nsec:381117000}, Mtime:syscall.Timespec{Sec:1584953801, Nsec:0}, Ctime:syscall.Timespec{Sec:1584953801, Nsec:376117000}}}
cloning dir path = fsutil.dirInfo{src:"/bin", dst:"/opt/dockerslim/artifacts/files/bin", perms:0x800001ed, sys:fsutil.SysStat{Ok:true, Uid:0x0, Gid:0x0, Atime:syscall.Timespec{Sec:1584950048, Nsec:277210000}, Mtime:syscall.Timespec{Sec:1575904988, Nsec:0}, Ctime:syscall.Timespec{Sec:1584950048, Nsec:270210000}}}
docker-slim: container stderr:
time="2020-03-23T09:00:58Z" level=info msg="sensor: args => []string{\"/opt/dockerslim/bin/docker-slim-sensor\"}"
time="2020-03-23T09:00:58Z" level=info msg="sensor: waiting for commands..."
time="2020-03-23T09:01:03Z" level=info msg="sensor: monitor starting..."
time="2020-03-23T09:01:03Z" level=info msg="fanmon: Run"
time="2020-03-23T09:01:03Z" level=info msg="ptmon: Run"
time="2020-03-23T09:01:03Z" level=info msg="ptmon: collector - exiting... status= 256"
time="2020-03-23T09:01:03Z" level=info msg="ptmon: processor - collector finished =>0"
time="2020-03-23T09:01:06Z" level=info msg="sensor: waiting for monitor to complete startup..."
time="2020-03-23T09:01:06Z" level=info msg="sensor: monitor started (true)..."
time="2020-03-23T09:02:35Z" level=info msg="sensor: 'stop' monitor command"
time="2020-03-23T09:02:35Z" level=info msg="sensor: waiting for monitor to finish..."
time="2020-03-23T09:02:35Z" level=info msg="fanmon: processor - stopping..."
time="2020-03-23T09:02:35Z" level=info msg="fanmon: collector - stopping...."
time="2020-03-23T09:02:35Z" level=warning msg="CopyFile(/usr/lib/liblzma.so.5,/opt/dockerslim/artifacts/files/usr/lib/liblzma.so.5) error: symlink liblzma.so.5.2.4 /opt/dockerslim/artifacts/files/usr/lib/liblzma.so.5: file exists"
time="2020-03-23T09:02:35Z" level=warning msg="CopyFile(/lib/libz.so.1,/opt/dockerslim/artifacts/files/lib/libz.so.1) error: symlink libz.so.1.2.11 /opt/dockerslim/artifacts/files/lib/libz.so.1: file exists"
time="2020-03-23T09:02:35Z" level=info msg="sensor: monitor stopped..."
time="2020-03-23T09:02:35Z" level=info msg="sensor: 'shutdown' command"
time="2020-03-23T09:02:35Z" level=info msg="sensor: done!"
docker-slim: end of container logs =============
docker-slim[build]: state=container.inspection.artifact.processing
docker-slim[build]: state=container.inspection.done
docker-slim[build]: state=building message='building optimized image'
docker-slim[build]: state=completed
docker-slim[build]: info=results status='MINIFIED BY 22.11X [452263354 (452 MB) => 20459253 (20 MB)]'
docker-slim[build]: info=results  image.name=clair image.size='20 MB' data=true
docker-slim[build]: info=results  artifacts.location='/opt/docker-slim/.docker-slim-state/images/987b8f01b40da6e628439d3c4dadbb0062bae4eee055d554517692122838f56c/artifacts'
docker-slim[build]: info=results  artifacts.report=creport.json
docker-slim[build]: info=results  artifacts.dockerfile.original=Dockerfile.fat
docker-slim[build]: info=results  artifacts.dockerfile.new=Dockerfile
docker-slim[build]: info=results  artifacts.seccomp=clair.fat-seccomp.json
docker-slim[build]: info=results  artifacts.apparmor=clair.fat-apparmor-profile
docker-slim[build]: state=done
docker-slim[build]: info=report file='slim.report.json'
```

**Comment by kcq** [comment]
Thanks a lot @rcomanne ! Will be useful for the repro :)

**Comment by kcq** [comment]
by the way, the `--http-probe-exit-on-failure` is true by default now :)
