### ISSUE TITLE
Error: could not find libjava.so

### ISSUE THREAD

**Issue by a18792721831** [docker-slim/docker-slim#142]
os:
Linux host-10-0-228-117 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

question:
Error: could not find libjava.so
Error: Could not find Java SE Runtime Environment.

process:
1. docker-slim build <image-id>
output:
docker-slim[build]: info=http.probe message='using default probe'
docker-slim[build]: state=started
docker-slim[build]: info=params target=billing-jenkins continue.mode=probe rt.as.user=true keep.perms=true
docker-slim[build]: state=image.inspection.start
docker-slim[build]: info=image id=sha256:6be130d0ec2ce783666533a79dcb46eed149d1e376135e4a44783f71d54c488f size.bytes=2345423912 size.human=2.3 GB
docker-slim[build]: info=image.users exe='[root]' all='[root]'
docker-slim[build]: info=image.stack index=0 name='<image-id>:latest' id='sha256:6be130d0ec2ce783666533a79dcb46eed149d1e376135e4a44783f71d54c488f'
docker-slim[build]: info=image.exposed_ports list='8080/tcp'
docker-slim[build]: state=image.inspection.done
docker-slim[build]: state=container.inspection.start
docker-slim[build]: info=container status=created name=dockerslimk_25094_20200413011056 id=8376e2ba2868621d759343cd43f99a08944c57fa5043455d547db47a54c60201
docker-slim[build]: info=cmd.startmonitor status=sent
docker-slim[build]: info=event.startmonitor.done status=received
docker-slim[build]: info=container name=dockerslimk_25094_20200413011056 id=8376e2ba2868621d759343cd43f99a08944c57fa5043455d547db47a54c60201 target.port.list=[32770] target.port.info=[8080/tcp => 0.0.0.0:32770] message='YOU CAN USE THESE PORTS TO INTERACT WITH THE CONTAINER'
docker-slim[build]: state=http.probe.starting message='WAIT FOR HTTP PROBE TO FINISH'
docker-slim[build]: info=continue.after mode=probe message='no input required, execution will resume when HTTP probing is completed'
docker-slim[build]: info=prompt message='waiting for the HTTP probe to finish'
docker-slim[build]: state=http.probe.running
docker-slim[build]: info=http.probe.ports count=1 targets='32770'
docker-slim[build]: info=http.probe.commands count=1 commands='GET /'
docker-slim[build]: info=http.probe.call status=error method=GET target=http://127.0.0.1:32770/ attempt=1 error='Get "http://127.0.0.1:32770/": read tcp 127.0.0.1:49886->127.0.0.1:32770: read: connection reset by peer' time=2020-04-13T01:11:08Z
docker-slim[build]: info=http.probe.call status=error method=GET target=http://127.0.0.1:32770/ attempt=2 error='Get "http://127.0.0.1:32770/": read tcp 127.0.0.1:49924->127.0.0.1:32770: read: connection reset by peer' time=2020-04-13T01:11:16Z
docker-slim[build]: info=http.probe.call status=error method=GET target=http://127.0.0.1:32770/ attempt=3 error='Get "http://127.0.0.1:32770/": read tcp 127.0.0.1:49962->127.0.0.1:32770: read: connection reset by peer' time=2020-04-13T01:11:24Z
docker-slim[build]: info=http.probe.call status=error method=GET target=http://127.0.0.1:32770/ attempt=4 error='Get "http://127.0.0.1:32770/": EOF' time=2020-04-13T01:11:32Z
docker-slim[build]: info=http.probe.call status=error method=GET target=http://127.0.0.1:32770/ attempt=5 error='Get "http://127.0.0.1:32770/": read tcp 127.0.0.1:50060->127.0.0.1:32770: read: connection reset by peer' time=2020-04-13T01:11:48Z
docker-slim[build]: info=http.probe.summary total=5 failures=5 successful=0
docker-slim[build]: state=http.probe.done warning=no.successful.calls
docker-slim[build]: info=event message='HTTP probe is done'
docker-slim[build]: state=container.inspection.finishing
docker-slim[build]: state=container.inspection.artifact.processing
docker-slim[build]: state=container.inspection.done
docker-slim[build]: state=building message='building optimized image'
docker-slim[build]: state=completed
docker-slim[build]: info=results status='MINIFIED BY 1004.66X [2345423912 (2.3 GB) => 2334543 (2.3 MB)]'
docker-slim[build]: info=results  image.name=<image-id>.slim image.size='2.3 MB' data=true
docker-slim[build]: info=results  artifacts.location='/usr/local/bin/docker-slim/.docker-slim-state/images/6be130d0ec2ce783666533a79dcb46eed149d1e376135e4a44783f71d54c488f/artifacts'
docker-slim[build]: info=results  artifacts.report=creport.json
docker-slim[build]: info=results  artifacts.dockerfile.original=Dockerfile.fat
docker-slim[build]: info=results  artifacts.dockerfile.new=Dockerfile
docker-slim[build]: info=results  artifacts.seccomp=<image-id>-seccomp.json
docker-slim[build]: info=results  artifacts.apparmor=<image-id>-apparmor-profile
docker-slim[build]: state=done
docker-slim[build]: info=report file='slim.report.json'
2. docker run -it -v /jenkins-war/:/jenkins-war/ <image-id>.slim
(yes,it's custom-made jenkins docker image)
out put:
Error: could not find libjava.so
Error: Could not find Java SE Runtime Environment.
3. slim.report.json
<details>
{
  "type": "build",
  "state": "done",
  "image_reference": "image-id",
  "system": {
    "type": "Linux",
    "release": "3.10.0-1062.1.2.el7.x86_64",
    "os": "unknown"
  },
  "source_image": {
    "id": "sha256:6be130d0ec2ce783666533a79dcb46eed149d1e376135e4a44783f71d54c488f",
    "name": "image-id:latest",
    "size": 2345423912,
    "size_human": "2.3 GB",
    "create_time": "2020-04-10T08:27:25Z",
    "all_names": [
      "image-id:latest"
    ],
    "Author": "jiayq <jiayq@startimes.com.cn>",
    "docker_version": "1.13.1",
    "architecture": "amd64",
    "user": "root",
    "exposed_ports": [
      "8080/tcp"
    ]
  },
  "minified_image_size": 2334543,
  "minified_image_size_human": "2.3 MB",
  "minified_image": "image-id.slim",
  "minified_image_has_data": true,
  "minified_by": 1004.6608316916844,
  "artifact_location": "/usr/local/bin/docker-slim/.docker-slim-state/images/6be130d0ec2ce783666533a79dcb46eed149d1e376135e4a44783f71d54c488f/artifacts",
  "container_report_name": "creport.json",
  "seccomp_profile_name": "image-id-seccomp.json",
  "apparmor_profile_name": "image-id-apparmor-profile",
  "image_stack": [
    {
      "is_top_image": true,
      "id": "sha256:6be130d0ec2ce783666533a79dcb46eed149d1e376135e4a44783f71d54c488f",
      "full_name": "image-id:latest",
      "repo_name": "image-id",
      "version_tag": "latest",
      "raw_tags": [
        "image-id:latest"
      ],
      "create_time": "2020-04-10T08:27:25Z",
      "new_size": 2345423912,
      "new_size_human": "2.3 GB",
      "instructions": [
        {
          "type": "FROM",
          "time": "2020-01-02T09:02:51Z",
          "is_nop": false,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 800537749,
          "size_human": "800 MB",
          "params": "scratch",
          "command_snippet": "FROM scratch",
          "comment": "Imported from -"
        },
        {
          "type": "MAINTAINER",
          "time": "2020-04-10T08:14:10Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "mail-name <mail-address>",
          "command_snippet": "MAINTAINER mail-name <mail-address>"
        },
        {
          "type": "USER",
          "time": "2020-04-10T08:14:10Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "[root]",
          "command_snippet": "USER [root]"
        },
        {
          "type": "ADD",
          "time": "2020-04-10T08:14:15Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 24185259,
          "size_human": "24 MB",
          "params": "file:a96d96647bb0a35576dc50dd4650ef6ba035adb6e27f4d170d87ad5b93cbf214 in /root/",
          "command_snippet": "ADD file:a96d96647bb0a35576dc50dd4650ef6ba03..."
        },
        {
          "type": "ADD",
          "time": "2020-04-10T08:15:21Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 365251435,
          "size_human": "365 MB",
          "params": "file:4f1e5975327fc85219c0e329cc173eac8537bc9227f02fc5530bf945a99c73d1 in /",
          "command_snippet": "ADD file:4f1e5975327fc85219c0e329cc173eac853..."
        },
        {
          "type": "COPY",
          "time": "2020-04-10T08:15:59Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 308379261,
          "size_human": "308 MB",
          "params": "dir:b8bebfde719d4588830eabd779516e582cff856d8b03547dbfcfa04247ada694 in /opt/oracle",
          "command_snippet": "COPY dir:b8bebfde719d4588830eabd779516e582cf..."
        },
        {
          "type": "COPY",
          "time": "2020-04-10T08:16:03Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 69165356,
          "size_human": "69 MB",
          "params": "dir:3098763949529cdec88a3501dc50741b3930eacef3486e84aad3431efc8ce9f5 in /rpm",
          "command_snippet": "COPY dir:3098763949529cdec88a3501dc50741b393..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:03Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "alias=vi=vim",
          "command_snippet": "ENV alias=vi=vim"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:03Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin",
          "command_snippet": "ENV PATH=/usr/local/sbin:/usr/local/bin:/usr..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:03Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "LANG=en_US",
          "command_snippet": "ENV LANG=en_US"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:04Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "LC_ALL=en_US",
          "command_snippet": "ENV LC_ALL=en_US"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:04Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "EDITOR=vi",
          "command_snippet": "ENV EDITOR=vi"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:04Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "MANPATH=:/usr/share/man:/usr/share/locale/man",
          "command_snippet": "ENV MANPATH=:/usr/share/man:/usr/share/local..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:04Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "LD_LIBRARY_PATH=/usr/lib:/usr/dt/lib:/usr/openwin/lib:/usr/sfw/lib:/usr/local/lib:/usr/local/ssl/lib:/usr/local/apr/lib:.",
          "command_snippet": "ENV LD_LIBRARY_PATH=/usr/lib:/usr/dt/lib:/us..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:04Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "PATH=/bin:/sbin:/usr/bin:/usr/sbin:/etc:/usr/local/bin:/usr/local/sbin:/usr/ccs/bin:/usr/ucb:/usr/sfw/bin:.",
          "command_snippet": "ENV PATH=/bin:/sbin:/usr/bin:/usr/sbin:/etc:..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:05Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "CC=gcc",
          "command_snippet": "ENV CC=gcc"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:05Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "ORACLE_BASE=/opt/oracle",
          "command_snippet": "ENV ORACLE_BASE=/opt/oracle"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:05Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "ORACLE_HOME=/opt/oracle/instantclient_11_2",
          "command_snippet": "ENV ORACLE_HOME=/opt/oracle/instantclient_11..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:05Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "ORACLE_SID=starboss",
          "command_snippet": "ENV ORACLE_SID=starboss"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:05Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "PATH=/opt/oracle/instantclient_11_2/sdk:/opt/oracle/instantclient_11_2:/bin:/sbin:/usr/bin:/usr/sbin:/etc:/usr/local/bin:/usr/local/sbin:/usr/ccs/bin:/usr/ucb:/usr/sfw/bin:.",
          "command_snippet": "ENV PATH=/opt/oracle/instantclient_11_2/sdk:..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:05Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "LD_LIBRARY_PATH=/opt/oracle/instantclient_11_2/:/lib64:/usr/lib64",
          "command_snippet": "ENV LD_LIBRARY_PATH=/opt/oracle/instantclien..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:06Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "CLASSPATH=:/opt/oracle/instantclient_11_2/jre:/opt/oracle/instantclient_11_2/jlib:/opt/oracle/instantclient_11_2/rdbms/jlib",
          "command_snippet": "ENV CLASSPATH=:/opt/oracle/instantclient_11_..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:06Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "NLS_LANG=AMERICAN_AMERICA.ZHS16GBK",
          "command_snippet": "ENV NLS_LANG=AMERICAN_AMERICA.ZHS16GBK"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:06Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "LIBXML2_HOME=/usr",
          "command_snippet": "ENV LIBXML2_HOME=/usr"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:06Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "LD_LIBRARY_PATH=/opt/oracle/instantclient_11_2/:/lib64:/usr/lib64:/usr/local/lib",
          "command_snippet": "ENV LD_LIBRARY_PATH=/opt/oracle/instantclien..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:06Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "PATH=/opt/oracle/instantclient_11_2/sdk:/opt/oracle/instantclient_11_2:/bin:/sbin:/usr/bin:/usr/sbin:/etc:/usr/local/bin:/usr/local/sbin:/usr/ccs/bin:/usr/ucb:/usr/sfw/bin:.:/opt/oracle/instantclient_11_2/lib:/opt/oracle/instantclient_11_2/bin:/opt/oracle/instantclient_11_2/sdk:/opt/oracle/instantclient_11_2:/bin:/sbin:/usr/bin:/usr/sbin:/etc:/usr/local/bin:/usr/local/sbin:/usr/ccs/bin:/usr/ucb:/usr/sfw/bin:.:/usr/bin",
          "command_snippet": "ENV PATH=/opt/oracle/instantclient_11_2/sdk:..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:06Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "LOCAL_LIB_PATH=/usr/local/lib",
          "command_snippet": "ENV LOCAL_LIB_PATH=/usr/local/lib"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:07Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "LIBRARY_PATH=/usr/lib:/opt/oracle/instantclient_11_2",
          "command_snippet": "ENV LIBRARY_PATH=/usr/lib:/opt/oracle/instan..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:07Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "CPLUS_INCLUDE_PATH=/opt/oracle/instantclient_11_2/sdk/include:/opt/oracle/instantclient_11_2/rdbms/public:/usr/include/libxml2",
          "command_snippet": "ENV CPLUS_INCLUDE_PATH=/opt/oracle/instantcl..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:07Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "C_INCLUDE_PATH=/usr/include/libxml2",
          "command_snippet": "ENV C_INCLUDE_PATH=/usr/include/libxml2"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:07Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "ulimit=-S -c unlimited",
          "command_snippet": "ENV ulimit=-S -c unlimited"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:07Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "OS=LINUX",
          "command_snippet": "ENV OS=LINUX"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:07Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "JAVA_HOME=/jdk1.8.0_111",
          "command_snippet": "ENV JAVA_HOME=/jdk1.8.0_111"
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:07Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "CLASSPATH=:/opt/oracle/instantclient_11_2/jre:/opt/oracle/instantclient_11_2/jlib:/opt/oracle/instantclient_11_2/rdbms/jlib:/jdk1.8.0_111/lib/dt.jar:/jdk1.8.0_111/lib/tools.jar",
          "command_snippet": "ENV CLASSPATH=:/opt/oracle/instantclient_11_..."
        },
        {
          "type": "ENV",
          "time": "2020-04-10T08:16:08Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "PATH=/opt/oracle/instantclient_11_2/sdk:/opt/oracle/instantclient_11_2:/bin:/sbin:/usr/bin:/usr/sbin:/etc:/usr/local/bin:/usr/local/sbin:/usr/ccs/bin:/usr/ucb:/usr/sfw/bin:.:/opt/oracle/instantclient_11_2/lib:/opt/oracle/instantclient_11_2/bin:/opt/oracle/instantclient_11_2/sdk:/opt/oracle/instantclient_11_2:/bin:/sbin:/usr/bin:/usr/sbin:/etc:/usr/local/bin:/usr/local/sbin:/usr/ccs/bin:/usr/ucb:/usr/sfw/bin:.:/usr/bin:/jdk1.8.0_111/bin",
          "command_snippet": "ENV PATH=/opt/oracle/instantclient_11_2/sdk:..."
        },
        {
          "type": "WORKDIR",
          "time": "2020-04-10T08:16:08Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "/root/gsoap-2.7",
          "command_snippet": "WORKDIR /root/gsoap-2.7",
          "system_commands": [
            "mkdir -p /root/gsoap-2.7"
          ]
        },
        {
          "type": "RUN",
          "time": "2020-04-10T08:18:21Z",
          "is_nop": false,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 215339063,
          "size_human": "215 MB",
          "command_snippet": "RUN find /rpm -type f|xargs rpm -i --force -...",
          "system_commands": [
            "find /rpm -type f|xargs rpm -i --force --nodeps"
          ]
        },
        {
          "type": "RUN",
          "time": "2020-04-10T08:18:23Z",
          "is_nop": false,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "command_snippet": "RUN chmod +x /root/gsoap-2.7",
          "system_commands": [
            "chmod +x /root/gsoap-2.7"
          ]
        },
        {
          "type": "RUN",
          "time": "2020-04-10T08:19:36Z",
          "is_nop": false,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 498108,
          "size_human": "498 kB",
          "command_snippet": "RUN ./configure",
          "system_commands": [
            "./configure"
          ]
        },
        {
          "type": "RUN",
          "time": "2020-04-10T08:20:28Z",
          "is_nop": false,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 26713762,
          "size_human": "27 MB",
          "command_snippet": "RUN make",
          "system_commands": [
            "make"
          ]
        },
        {
          "type": "RUN",
          "time": "2020-04-10T08:20:30Z",
          "is_nop": false,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 11635619,
          "size_human": "12 MB",
          "command_snippet": "RUN make install",
          "system_commands": [
            "make install"
          ]
        },
        {
          "type": "RUN",
          "time": "2020-04-10T08:20:54Z",
          "is_nop": false,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 308379237,
          "size_human": "308 MB",
          "command_snippet": "RUN chmod -R 755 /opt/oracle",
          "system_commands": [
            "chmod -R 755 /opt/oracle"
          ]
        },
        {
          "type": "RUN",
          "time": "2020-04-10T08:20:56Z",
          "is_nop": false,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "command_snippet": "RUN mkdir /tmp",
          "system_commands": [
            "mkdir /tmp"
          ]
        },
        {
          "type": "RUN",
          "time": "2020-04-10T08:20:57Z",
          "is_nop": false,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "command_snippet": "RUN mkdir /jenkins-war/",
          "system_commands": [
            "mkdir /jenkins-war/"
          ]
        },
        {
          "type": "RUN",
          "time": "2020-04-10T08:27:11Z",
          "is_nop": false,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 215339063,
          "size_human": "215 MB",
          "command_snippet": "RUN find /rpm -type f|xargs rpm -i --force -...",
          "system_commands": [
            "find /rpm -type f|xargs rpm -i --force --nodeps"
          ]
        },
        {
          "type": "EXPOSE",
          "time": "2020-04-10T08:27:25Z",
          "is_nop": true,
          "local_image_exits": false,
          "layer_index": 0,
          "size": 0,
          "params": "8080/tcp",
          "command_snippet": "EXPOSE 8080/tcp"
        },
        {
          "type": "ENTRYPOINT",
          "time": "2020-04-10T08:27:25Z",
          "is_last_instruction": true,
          "is_nop": true,
          "is_exec_form": true,
          "local_image_exits": true,
          "layer_index": 0,
          "size": 0,
          "params": "[\"java\",\"-jar\",\"/jenkins-war/jenkins.war\",\"--httpPort=8080\"]",
          "command_snippet": "ENTRYPOINT [\"java\",\"-jar\",\"/jenkins-war/jenk...",
          "raw_tags": [
            "image-id:latest"
          ]
        }
      ]
    }
  ]
}
</details>

explain:
image-id replace real image id/name
mail-name replace real mail name
mail-addr replace real mail address

is a real issue ?

please, thanks!

**Comment by kcq** [comment]
@a18792721831 curious what you used for the base image... What kind of OS image is it? Can you share the container logs when `docker-slim` runs? You can get them by adding the `--show-clogs` parameter to the `docker-slim build` command (or directly from Docker with the usual `docker logs` command).

**Comment by a18792721831** [comment]
close，thanks。

**Comment by paulcalabro** [comment]
I resolved this error by adding the following flag:

```
--include-path=/usr/lib/x86_64-linux-gnu/ 
```
