### ISSUE TITLE
How to rename the image name and tag after slim build?

### ISSUE THREAD

**Issue by heshenheng** [docker-slim/docker-slim#146]
After slim build,the new docker image name is XXX.slim and tag is latest,but this isn't what I want.

**Comment by kerwin6182828** [comment]
docker image tag <current_image_name> <new_image_name>

**Comment by heshenheng** [comment]
thanks kerwin and I know the way you said it,but I want to know the way when docker-silm building the new image,rather then after slim build.

**Comment by kcq** [comment]
@heshenheng you can use the `--tag` parameter to have a different image: `docker-slim build --tag new-image-name:custom-tag-name your-image`

**Comment by heshenheng** [comment]
@kcq thank you very much!
