### ISSUE TITLE
Node application gets all its dependencies stripped when minified

### ISSUE THREAD

**Issue by jlengrand** [docker-slim/docker-slim#149]
Hey there!

I'm just getting started with `docker-slim`, so apologies if my question has been covered already.

I'm building a Dockerfile for [this project](https://github.com/carbon-app/carbon) (for fun). You can see the latest version of my Dockerfile [here](https://github.com/jlengrand/carbon/blob/feature/docker/Dockerfile). 

Here it is just in case for reference : 

```Dockerfile 
FROM mhart/alpine-node:12 AS builder

RUN apk update && apk add curl bash

WORKDIR /app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn build
RUN npm prune --production
RUN curl -sfL https://install.goreleaser.com/github.com/tj/node-prune.sh | bash -s -- -b /usr/local/bin
RUN /usr/local/bin/node-prune

FROM mhart/alpine-node:12

WORKDIR /app
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/components ./components
COPY --from=builder /app/lib ./lib
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/pages ./pages
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./next.config.js
COPY --from=builder /app/LICENSE ./LICENSE
COPY --from=builder /app/package.json ./package.json
EXPOSE 3000
CMD [ "yarn", "start" ]
```

The latest image I want to slim down can be found on [the Docker hub](https://hub.docker.com/repository/docker/julienlengrand/carbon.now.sh).

Version of docker-slim is `docker-slim version darwin|Transformer|1.29.0|latest|latest`

When running my build command, I cannot seem to probe my port 3000 myself. It seems like consequently, `docker-slim` strips too much of it and the end result misses a lot of node dependencies, css files and the like. 

This is the command I used since probing is enabled by default: 
```
$ docker-slim build julienlengrand/carbon.now.sh:latest
```

All my attempts to reach localhost:3000 result in a 404 (even though somehow probing finishes successfully?).

Here is the complete log of the run : 

```
➜  carbon git:(feature/docker) ✗ docker-slim build julienlengrand/carbon.now.sh:latest
docker-slim[build]: info=http.probe message='using default probe'
docker-slim[build]: state=started
docker-slim[build]: info=params target=julienlengrand/carbon.now.sh:latest continue.mode=probe rt.as.user=true keep.perms=true
docker-slim[build]: state=image.inspection.start
docker-slim[build]: info=image id=sha256:a672815ed93fab8e63f6425f79e13b6ecf507655feecebbd5b3feb263de08c6e size.bytes=343045348 size.human=343 MB
docker-slim[build]: info=image.stack index=0 name='mhart/alpine-node:12' id='sha256:9ee68cad5b56783818ecde758eee8c8130a4882e7ae4e91da9bb75c626ac473d'
docker-slim[build]: info=image.stack index=1 name='julienlengrand/carbon.now.sh:latest' id='sha256:a672815ed93fab8e63f6425f79e13b6ecf507655feecebbd5b3feb263de08c6e'
docker-slim[build]: info=image.exposed_ports list='3000'
docker-slim[build]: state=image.inspection.done
docker-slim[build]: state=container.inspection.start
docker-slim[build]: info=container status=created name=dockerslimk_67502_20200520154400 id=9bdbdff0eb783fb2dc0288f969c25d80bf1b033482294b25ea7891af27794317
docker-slim[build]: info=cmd.startmonitor status=sent
docker-slim[build]: info=event.startmonitor.done status=received
docker-slim[build]: info=container name=dockerslimk_67502_20200520154400 id=9bdbdff0eb783fb2dc0288f969c25d80bf1b033482294b25ea7891af27794317 target.port.list=[32779] target.port.info=[3000/tcp => 0.0.0.0:32779] message='YOU CAN USE THESE PORTS TO INTERACT WITH THE CONTAINER'
docker-slim[build]: state=http.probe.starting message='WAIT FOR HTTP PROBE TO FINISH'
docker-slim[build]: info=continue.after mode=probe message='no input required, execution will resume when HTTP probing is completed'
docker-slim[build]: info=prompt message='waiting for the HTTP probe to finish'
docker-slim[build]: state=http.probe.running
docker-slim[build]: info=http.probe.ports count=1 targets='32779'
docker-slim[build]: info=http.probe.commands count=1 commands='GET /'
docker-slim[build]: info=http.probe.call status=200 method=GET target=http://127.0.0.1:32779/ attempt=1  time=2020-05-20T15:44:13Z
docker-slim[build]: info=http.probe.summary total=1 failures=0 successful=1
docker-slim[build]: state=http.probe.done
docker-slim[build]: info=event message='HTTP probe is done'
docker-slim[build]: state=container.inspection.finishing
docker-slim[build]: state=container.inspection.artifact.processing
docker-slim[build]: state=container.inspection.done
docker-slim[build]: state=building message='building optimized image'
docker-slim[build]: state=completed
docker-slim[build]: info=results status='MINIFIED BY 4.72X [343045348 (343 MB) => 72631258 (73 MB)]'
docker-slim[build]: info=results  image.name=julienlengrand/carbon.now.sh.slim image.size='73 MB' data=true
docker-slim[build]: info=results  artifacts.location='/tmp/docker-slim-state/.docker-slim-state/images/a672815ed93fab8e63f6425f79e13b6ecf507655feecebbd5b3feb263de08c6e/artifacts'
docker-slim[build]: info=results  artifacts.report=creport.json
docker-slim[build]: info=results  artifacts.dockerfile.original=Dockerfile.fat
docker-slim[build]: info=results  artifacts.dockerfile.new=Dockerfile
docker-slim[build]: info=results  artifacts.seccomp=julienlengrand-carbon.now.sh-seccomp.json
docker-slim[build]: info=results  artifacts.apparmor=julienlengrand-carbon.now.sh-apparmor-profile
docker-slim[build]: state=done
docker-slim[build]: info=report file='slim.report.json'
```

Just let me know if I'm missing anything, I'll keep diving as well on my end. 

Thanks in advance!

**Comment by jlengrand** [comment]
I do see in the slim report that port 3000 is marked as export, so at least that part of the config is picked up properly.

**Comment by jlengrand** [comment]
Ok, doing this seems to generate a fine working image `$ docker-slim build --include-path=/app  julienlengrand/carbon.now.sh:latest` while shaving 20Mb off my image, which is always welcome. It still feels quite unoptimized yet, given that 280mb of stuff is in the /app folder :D

**Comment by kcq** [comment]
@jlengrand We'll figure this out :) One of the potential reasons for this is dynamic client-side templates... Let me investigate and i'll update asap.

**Comment by kcq** [comment]
@jlengrand here's a better command version: `docker-slim build --include-path=/app/.next julienlengrand/carbon.now.sh` and it should get you an image that's 99MB (giving you ~3.5x reduction in size, which is what I got in my test). Still investigating if http probing and its new crawling capability can help too...

**Comment by jlengrand** [comment]
Hey there! Thanks for looking into it! Let me check it out :).

**Comment by jlengrand** [comment]
Alright so I'm getting some warnings in the console about missing dependencies, and also some missing CSS files in the console, but it seems like the functionality is actually working indeed!

Thanks a lot for the help :). 

For reference : 

```
➜  carbon git:(feature/docker) ✗ docker run -p 3000:3000 julienlengrand/carbon.now.sh.slim:latest
yarn run v1.22.4
$ next start
The module 'react-dom' was not found. Next.js requires that you include it in 'dependencies' of your 'package.json'. To add it, run 'npm install react-dom'
> Ready on http://localhost:3000
```

and 

![image](https://user-images.githubusercontent.com/921666/82765701-32b03080-9e19-11ea-8b1a-8d1562c34f29.png)

**Comment by jlengrand** [comment]
Something interesting BTW, I tried using docker slim with and without squashing the image first. 
It appears that docker slim is actually being more efficient at slimming down the non squashed image now :).

```bash
➜  carbon git:(feature/docker) ✗ docker images
REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
julienlengrand/carbon.now.sh.squashed.slim   latest              f3d2078d3650        12 seconds ago      104MB
julienlengrand/carbon.now.sh.slim            latest              e3532f2ad09c        7 minutes ago       99.4MB
julienlengrand/carbon.now.sh.squashed.slim   <none>              8c0d8ac87f74        2 days ago          273MB
julienlengrand/carbon.now.sh.squashed        latest              b09b0e3206f8        2 days ago          297MB
julienlengrand/carbon.now.sh                 latest              a672815ed93f        8 days ago          343MB
```

(The older versions from 2 days ago have `/app` as path, while the new ones have `/app/.next`

**Comment by kcq** [comment]
@jlengrand including the public directory should take care of those (most of them, at least): `docker-slim build --include-path=/app/.next --include-path=/app/public julienlengrand/carbon.now.sh` Switching themes seemed to work for me even without including that directory.

**Comment by jlengrand** [comment]
Yes, same here! The application complains, but is running fine :).

In case you're interested, I wrote a post about all the steps I took. https://lengrand.fr/ghost/#/editor/post/5ebfe0c8e7e3d3679366208a/. In the last stretch, docker slim was definitely the biggest winner. Well done!

**Comment by jlengrand** [comment]
Closing the issue as you seem to have found the main problem. Thanks again!

**Comment by kcq** [comment]
Great blog post @jlengrand ! i also created an example for it in the examples repo: https://github.com/docker-slim/examples/tree/master/3rdparty/carbon-now-sh

**Comment by jlengrand** [comment]
Hey there, thanks! Thanks for referencing, looks good :). Note that I used that experience to learn Docker, not sure how fair it is to compare.

I like it a lot though, the end image is super clean!

**Comment by kcq** [comment]
That's a great learning experience and it also shows that you have to know a lot to optimize things manually :)

**Comment by jlengrand** [comment]
> That's a great learning experience and it also shows that you have to know a lot to optimize things manually :)

It is! I was simply referring to what you named 'the hard way' in your README. 
I added your example on top of my blog post so people get redirected to it :).

Have a great weekend!
