### ISSUE TITLE
cacert.pem is not found after docker-slim

### ISSUE THREAD

**Issue by arcoyk** [docker-slim/docker-slim#165]
Hi

Thank you for the great repo.

I'm trying to build an image of [gensim](https://github.com/RaRe-Technologies/gensim) server. It seems like docker-slim deletes necessary file(s).

# Repo for reproduction
here: https://github.com/arcoyk/flask-gensim-cacert

# Dockerfile
```
FROM debian
RUN apt update
RUN apt install -y python3 python3-pip
RUN pip3 install --no-cache-dir gensim flask
RUN apt clean
EXPOSE 80
ADD ./app ./app
ENV FLASK_APP test.py
CMD cd app && flask run --host='0.0.0.0' --port=80
```

# Error
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/certifi/cacert.pem'
```

this error occurs on...
https://github.com/python/cpython/blob/41761933c1c30bb6003b65eef1ba23a83db4eae4/Lib/importlib/resources.py#L91

# How to reproduce the bug
```
git clone git@github.com:arcoyk/flask-gensim-cacert.git
docker build -t flask-image .
docker-slim build flask-image
docker run -p 80:80 flask-image.slim 
```

# Notes
This repo includes > 300MB file (Word2Vec model) which may take time to clone.
docker image before docker-slim works.

# Versions
Docker version 19.03.12, build 48a66213fe
docker-slim version darwin|Transformer|1.32.0|latest|latest

**Comment by kcq** [comment]
Thanks for the detailed repro information @arcoyk ! It's super helpful! looking into it... and will have an update soon

**Comment by kcq** [comment]
There's a couple of options...

With the Dockerfile you have you can use the --include-path flag to make sure the cacert.pem file is included:
`docker-slim build --include-path /usr/local/lib/python3.7/dist-packages/certifi/cacert.pem flask-image`

Another option is to use an older debian distro:
```
FROM debian:stretch
RUN apt update
RUN apt install -y python3 python3-pip
RUN pip3 install --no-cache-dir gensim flask
RUN apt clean
EXPOSE 80
ADD ./app ./app
WORKDIR /app
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV FLASK_APP test.py
CMD flask run --host='0.0.0.0' --port=80
```

**Comment by arcoyk** [comment]
Confirmed both of them works! Thank you again for the super great repo!

**Comment by deepanprabhu** [comment]
so the above approach did not work for me,
I ended up adding the certificate to docker image and docker slim had no issues,
![image](https://user-images.githubusercontent.com/11621168/120939521-4e594280-c6cd-11eb-9c7e-5c5e09479685.png)
