### ISSUE TITLE
Chaos input when pressed some comb-key

### ISSUE THREAD

**Issue by coanor** [docker-slim/docker-slim#170]
I'm using Iterm2 on Mac(10.14.6). When Pressing some comb-key like left+up, the UI display(occasionally) like this:

```
>>>>> >>> >>> >>> df>>> dfd?>>> dfd?[C>>> dfd?[C?[>>> dfd?[C?[B?[C?[Bd?[C?[B?[B?[C?[C?[B?[C?[B?[C?[Bas
```

I have to use `ctrl + l` to clean the chaos output, then I get the expected display. Is this a bug(maybe a `go-prompt` package bug)? I think frequently pressing `left` and `up` is ok to edit exists inputs, but it's too easy to press them at the same time, then the display crached.

**Comment by x-private-one** [comment]
@coanor it is possible that it's related to the `go-prompt` package... Silly question... what do you mean by the `up` key? Do you mean left `option` key?

**Comment by kcq** [comment]
@coanor it is possible that it's related to the go-prompt package... Silly question... what do you mean by the up key? Do you mean left option key?

**Comment by kcq** [comment]
Looks like we have a go-prompt bug report for this behavior in iterm2: https://github.com/c-bata/go-prompt/issues/213

**Comment by kcq** [comment]
closing this for now given that it's related to an upstream library behavior/bug
