### ISSUE TITLE
Sticky bits aren't preserved

### ISSUE THREAD

**Issue by ns-wkso** [docker-slim/docker-slim#184]
Expected Behavior
=================
/usr/bin/sudo has same permission/sticky bit as fat image.

---
Actual Behavior
=================
Sticky bit missing on sudo, rendering it useless.

---
Steps to Reproduce the Problem
===============================
I'm trying to setup an ubuntu container people can use for development.   But the slimmed image's /usr/bin/sudo does not have the sticky bit set.  I even tried setting it via the :octal perm#uid#gid syntax:

docker-slim build --target docker-slim-tmp-fat-image.61913.20210308215910 --http-probe=false  --continue-after=1  --exclude-pattern=/usr/share/doc    --include-shell  --include-path='**/usr/bin/sudo:1777#0#0**' 

$ sudo docker run -it docker-slim-tmp-fat-image.61913.20210308215910.slim
bash-5.0$                                                                                                                                                                    bash-5.0$ ls -l /usr/bin/sudo
-**rwxrwxrwx** 1 root 0 166056 Jan 19 14:21 /usr/bin/sudo

In fact, I had to specify include-path, as otherwise sudo would be missing.  Along those lines, the image is only 10mb, from 6gb fat image:

wkso@prodeng03:~/src/ns/jenkins-pipeline/dockerfiles/Build$ sudo docker images
REPOSITORY                                            TAG                IMAGE ID       CREATED          SIZE
docker-slim-tmp-fat-image.61913.20210308215910.slim   latest             b243cfe8dae9   44 seconds ago   10.4MB
docker-slim-tmp-fat-image.61913.20210308215910        latest             a83affd13fc1   2 hours ago      6.84GB

---
Specifications
=================
  - Version: $ ~/docker-slim --version
docker-slim version linux|Transformer|1.34.0|a5cb54043b3ab3cf747165aad745f19db680434e|2021-01-29_10:00:49PM
  - Platform: ubuntu

**Comment by kcq** [comment]
Thanks for reporting the problem @ns-wkso ! Working on reproducing the condition...

**Comment by ns-wkso** [comment]
Just wanted to follow up to see if you can reproduce the problem and if you need anything from me. Thanks in advance!

**Comment by kcq** [comment]
Looks like the sticky bit does get preserved, but the setuid bit isn't. I assume that's what you'd like to keep with the `sudo` executable. This behavior is related to how the docker copy operation works ( https://github.com/moby/moby/issues/37830 ). Looking for a workaround. Also adding an ability to set the extra bits (setuid, setgid, and sticky bit; not possible yet) in addition to the permission bits (possible now).

**Comment by kcq** [comment]
the latest release (1.35.1) should address the issue... @ns-wkso do you mind double checking if it's working for you?
