### ISSUE TITLE
php container not created: dslim/docker-slim:1.32.0 vs latest (1.34.0)

### ISSUE THREAD

**Issue by michabbb** [docker-slim/docker-slim#188]
hi there, 

pardon, i didn´t use dslim for quit a while. i created my slim PHP container in the past with dslim:1.32.0 which worked nice.
but with latest. the slim does *NOT* get created ;(

cmd 1.32.0:

`docker run --rm -v $HOME/docker/images/php/7.4:/app -w /app -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim:1.32.0 build --http-probe --dockerfile Dockerfile --include-exe --include-shell --include-path-file /app/.includes --tag php:7.4-fpm.slim .`

[and here´s the output](https://gist.github.com/michabbb/532b5309be1f70c3e5b1470b5cf96e1f).

```
REPOSITORY                   TAG                    IMAGE ID       CREATED          SIZE
php                          7.4-fpm.slim           5dfea62e19a9   34 seconds ago   306MB
php.fat                      7.4-fpm.slim           940031f6ef16   41 minutes ago   748MB
```

so that works, but with "latest", [the output](https://gist.github.com/michabbb/64e4216b94a0f819d12bf114218f8550) is much different.

and after that, there is no `php:7.4-fpm.slim` container:

```
REPOSITORY                   TAG                    IMAGE ID       CREATED             SIZE
php.fat                      7.4-fpm.slim           940031f6ef16   About an hour ago   748MB
php                          7.4-fpm                40b8d01ab471   About an hour ago   748MB
```

does anybody know what has changed or is my build cmd wrong ?
thanks for any help !!!

**Comment by kcq** [comment]
Thanks for reporting this! Trying to repro...

**Comment by kcq** [comment]
Thanks for providing the command output for both versions! It looks like with the latest version `docker-slim` terminates when the http probes fail. It happens by default, but you can change this behavior using the `--http-probe-exit-on-failure` flag (set it to false: `--http-probe-exit-on-failure=false`). Another option is to disable http probing completely (`--http-probe=false`). PHP containers actually need fast-cgi probes (not regular http probes), so you should be ok disabling http probes at this point in time (support for fast-cgi probes will be available in the near future).

**Comment by michabbb** [comment]
@kcq thanks a lot for taking your time looking into this, i will test it and let you know, thanks a lot !!

**Comment by michabbb** [comment]
@kcq [the output](https://gist.github.com/michabbb/d0cc557bee5feef51eca6fec59225bea) is much less now, but the new image has been created. thanks ! 👍

**Comment by michabbb** [comment]
just a notice: the "docker:latest" seems not to be up2date, cause i get this notice:

> Your version of DockerSlim is out of date!
