### ISSUE TITLE
Cannot Add Multiple Tags

### ISSUE THREAD

**Issue by ProfessorManhattan** [docker-slim/docker-slim#194]
Expected Behavior
=================

DockerSlim should allow you to pass multiple image tags.

---
Actual Behavior
=================

You can only assign one tag. If you want to tag something with two tags then you have to run the docker-slim command twice with the two different tags.

**Comment by kcq** [comment]
@ProfessorManhattan It's assumed if you need additional tags you'd use `docker tag` on the minified image produced by the `docker-slim build` command. Do you mind sharing a bit more about your use case? Curious to learn why you need multiple tags.

Adding support for more than one custom tag should be available pretty soon.

**Comment by ProfessorManhattan** [comment]
Hey @kcq -- thanks, I didn't think of that. `docker build` supports multiple tags though. My use case is for tagging something as :slim and :0.0.0-slim

**Comment by kcq** [comment]
This ability is already in master and it'll be there in the next released binary too. Here's an example where the optimized nginx image ends up with 3 different tags: `docker-slim build --tag nginx:slim --tag nginx-minified --tag nginx-min:slim nginx`
