### ISSUE TITLE
--tag not working

### ISSUE THREAD

**Issue by naanunaane** [docker-slim/docker-slim#202]
Expected Behavior
=================
Using the --tag for the docker-slim build command is supposed to result in the optimised image being tagged with that name

---
Actual Behavior
=================
The final tagged image is still <original_image_name.slim>:latest

---
Steps to Reproduce the Problem
===============================

  1. Use the command to build an optimised image:
  docker-slim build --http-probe-off --include-path=/usr/local --continue-after 1 --target eventflow/rfunction:rsi --tag eventflow/rfunction.slim:rsi
  
  2. Replace it with any of your image target. However, this is what I see for the target image with name eventflow/rfunction:rsi. Final image created is eventflow/rfunction.slim:latest instead of eventflow/rfunction.slim:rsi
![Screenshot from 2021-06-16 23-35-45](https://user-images.githubusercontent.com/48794849/122270268-c3155380-cefb-11eb-98af-31ec7bb03436.png)
 

---
Specifications
=================
  - docker-slim version: linux|Transformer|1.36.0|5dad378523ed9d53f6e5de21f6b98f07da4f7d59|2021-06-13_02:46:04AM
  - OS:version :: Ubuntu: 18.04.3 LTS (Bionic Beaver)

**Comment by x-private-one** [comment]
still trying to repro...

**Comment by kcq** [comment]
still trying to repro it

**Comment by kcq** [comment]
@naanunaane do you mind trying 1.36.1 to see if we can get additional info about what's going on (  https://github.com/docker-slim/docker-slim/releases/tag/1.36.1 )

**Comment by naanunaane** [comment]
@kcq, this worked after I updated to the 1.36.1 version. Thanks.

**Comment by kcq** [comment]
nice!
