### ISSUE TITLE
docker-slim latest version seems not working properly with the java_standard example

### ISSUE THREAD

**Issue by justinzhf** [docker-slim/docker-slim#222]
Expected Behavior
=================
Run the latest docker-slim(1.36.4) with the java_standard example(https://github.com/docker-slim/examples/tree/master/java_standard). Expect that it could run successfully.

---
Actual Behavior
=================
The http-probe step just fails. Then it causes the docker-slim to fail.

---
Steps to Reproduce the Problem
===============================
OS Debian. Run the commands under java_standard(https://github.com/docker-slim/examples/tree/master/java_standard) directory.
  1. run `jar.build.command`
  1. run `build.command`
  1. run `slim.command`
In my machine, the output is as following:
docker-slim: message='join the Gitter channel to ask questions or to share your feedback' info='https://gitter.im/docker-slim/community'
docker-slim: message='join the Discord server to ask questions or to share your feedback' info='https://discord.gg/9tDyxYS'
docker-slim: message='Github discussions' info='https://github.com/docker-slim/docker-slim/discussions'
cmd=build info=param.http.probe message='using default probe'
cmd=build state=started
cmd=build info=params target='my/java-dropwizard-standard' continue.mode='probe' rt.as.user='true' keep.perms='true' tags=''
cmd=build state=image.inspection.start
cmd=build info=image id='sha256:76a39485bf7f3ea70bf1ca54133ffabda6321e595f4bacdc42ed0096f9989433' size.bytes='540018052' size.human='540 MB'
cmd=build info=image.stack index='0' name='openjdk:8' id='sha256:08121337b7a4972212918a3fa235acd34442af8c2dafbea92fa7a7f54f9dc2c4'
cmd=build info=image.stack id='sha256:76a39485bf7f3ea70bf1ca54133ffabda6321e595f4bacdc42ed0096f9989433' index='1' name='my/java-dropwizard-standard:latest'
cmd=build info=image.exposed_ports list='8080'
cmd=build state=image.inspection.done
cmd=build state=container.inspection.start
cmd=build info=container status='created' name='dockerslimk_224247_20210915150624' id='88093865f00261df5c1b6435518ac7237a39125be4830d3f7293bc09b9210017'
cmd=build info=cmd.startmonitor status='sent'
cmd=build info=event.startmonitor.done status='received'
cmd=build info=container target.port.list='10069' target.port.info='8080/tcp => 0.0.0.0:10069' message='YOU CAN USE THESE PORTS TO INTERACT WITH THE CONTAINER' name='dockerslimk_224247_20210915150624' id='88093865f00261df5c1b6435518ac7237a39125be4830d3f7293bc09b9210017'
cmd=build state=http.probe.starting message=WAIT FOR HTTP PROBE TO FINISH
cmd=build info=continue.after mode='probe' message='no input required, execution will resume when HTTP probing is completed'
cmd=build prompt='waiting for the HTTP probe to finish'
cmd=build state=http.probe.running
cmd=build info=http.probe.ports count='1' targets='10069'
cmd=build info=http.probe.commands count='1' commands='GET /'
cmd=build info=http.probe.call error='Get "http://127.0.0.1:10069/": read tcp 127.0.0.1:11532->127.0.0.1:10069: read: connection reset by peer' time='2021-09-15T15:06:36Z' status='error' method='GET' target='http://127.0.0.1:10069/' attempt='1'
cmd=build info=http.probe.call status='error' method='GET' target='http://127.0.0.1:10069/' attempt='2' error='Get "http://127.0.0.1:10069/": read tcp 127.0.0.1:11570->127.0.0.1:10069: read: connection reset by peer' time='2021-09-15T15:06:44Z'
cmd=build info=http.probe.call time='2021-09-15T15:06:52Z' status='error' method='GET' target='http://127.0.0.1:10069/' attempt='3' error='Get "http://127.0.0.1:10069/": read tcp 127.0.0.1:11578->127.0.0.1:10069: read: connection reset by peer'
cmd=build info=http.probe.call attempt='4' error='Get "http://127.0.0.1:10069/": read tcp 127.0.0.1:11616->127.0.0.1:10069: read: connection reset by peer' time='2021-09-15T15:07:00Z' status='error' method='GET' target='http://127.0.0.1:10069/'
cmd=build info=http.probe.call attempt='5' error='Get "http://127.0.0.1:10069/": read tcp 127.0.0.1:11654->127.0.0.1:10069: read: connection reset by peer' time='2021-09-15T15:07:08Z' status='error' method='GET' target='http://127.0.0.1:10069/'
^Ccmd=build info=container status='crashed' id='88093865f00261df5c1b6435518ac7237a39125be4830d3f7293bc09b9210017'
time="2021-09-15T23:07:11+08:00" level=fatal msg="KillContainer: docker-slim received SIGINT, killing container 88093865f00261df5c1b6435518ac7237a39125be4830d3f7293bc09b9210017" app=docker-slim command=build component=container.inspector

---
Specifications
=================
  - Version: 1.36.4
  - Platform: Debian

**Comment by kcq** [comment]
thank you for catching the failure @justinzhf ! let me investigate a bit

**Comment by justinzhf** [comment]
> thank you for catching the failure @justinzhf ! let me investigate a bit

Hi, @kcq thanks for your reply! Have you figured out the cause of the failure? If not, do you know if there exists a certain version that' able to slim the java application?
