### ISSUE TITLE
Examples and Tips & Tricks

### ISSUE THREAD

**Issue by ProfessorManhattan** [docker-slim/docker-slim#238]
Hey, I love this product but I feel like I'm not utilizing it to its fullest. I have run into the problem where I want to include a binary in a build so I use something like `--include-path /usr/bin/jq`. However, it fails to run after compiling because `jq` requires extra libs. I find those libs out by running `ldd /usr/bin/jq` but its a very tedious process for something that could probably be automated.

I am also unsure of the difference between `--include-path`, `--include-bin`, `--include-bin-file`, `--preserve-path`, and `--preserve-path-file`. Can I use any of these options to automatically detect the shared libs that a binary relies on?

Anyway, my final ask is for a set of examples that illustrate which commands I should be using any why. Thank you!

**Comment by kcq** [comment]
The `--include-bin` and `--include-exe` should be useful with `jq`. 

The `--include-bin /usr/bin/jq` param should include `/usr/bin/jq` and its binary dependencies (the shared objects jq imports), so you wouldn't need to explicitly add those by hand.

The `--include-exe jq` is similar to `--include-bin`, but it also allows you to specify just the executable name. When you do that it'll find the executable in one of the PATH locations in your container image.

**Comment by kcq** [comment]
converting this issue to discussion...
