### ISSUE TITLE
Whenever I search for your project, I get pants.

### ISSUE THREAD

**Issue by mahalel** [docker-slim/docker-slim#244]
Expected Behavior
=================
DDG/Google search for "docker slim"

Receive link to this project.

---
Actual Behavior
=================
Receive images of pants.

---
Steps to Reproduce the Problem
===============================
As above.

(On a more serious note, thank you for a cool project 👍 )

**Comment by kcq** [comment]
@mahalel This is a known problem and we are exploring all possible options to fix it including eliminating all slim pants and bringing back cargo pants in style :-)
