### ISSUE TITLE
build docker-slim failed on aarch64 machine

### ISSUE THREAD

**Issue by vanloswang** [docker-slim/docker-slim#25]
``` bash
go version
```

go version go1.6.2 linux/arm64

``` bash
# go env
```

GOARCH="arm64"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_arm64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

Build docker-slim aarch64 machine reports such an error:
# github.com/cloudimmunity/docker-slim/sensor/monitors/ptrace

../../vendor/src/github.com/cloudimmunity/docker-slim/sensor/monitors/ptrace/monitor.go:91: regs.Orig_rax undefined (type syscall.PtraceRegs has no field or method Orig_rax)
../../vendor/src/github.com/cloudimmunity/docker-slim/sensor/monitors/ptrace/monitor.go:99: regs.Rax undefined (type syscall.PtraceRegs has no field or method Rax)

CC https://github.com/docker-slim/docker-slim/issues/6, meet such an error.

**Comment by vanloswang** [comment]
The definations is as follow in golang source code src/syscall/ztypes_linux_amd64.go:

type PtraceRegs struct {
    R15      uint64
    R14      uint64
    R13      uint64
    R12      uint64
    Rbp      uint64
    Rbx      uint64
    R11      uint64
    R10      uint64
    R9       uint64
    R8       uint64
    Rax      uint64
    Rcx      uint64
    Rdx      uint64
    Rsi      uint64
    Rdi      uint64
    Orig_rax uint64
    Rip      uint64
    Cs       uint64
    Eflags   uint64
    Rsp      uint64
    Ss       uint64
    Fs_base  uint64
    Gs_base  uint64
    Ds       uint64
    Es       uint64
    Fs       uint64
    Gs       uint64
}

**Comment by vanloswang** [comment]
This is a golang compiler issue.

**Comment by vanloswang** [comment]
@BenHall @kcq @wrwrwr @pydima @geekthattweaks 
Golang may not fix the difference between cpu arch, so we need to change the code fix such an issue in sensor/monitors/ptrace/monitor.go.

**Comment by kcq** [comment]
Yes, ARM isn't supported yet. Definitely need help with it. It'll be great if you want to jump in and add support for it :-)

**Comment by kcq** [comment]
Moving ARM support to the Wishlist. Ping me if you want to help :-)
