### ISSUE TITLE
Need to migrate the inline command flag definitions in `build` and other commands to the corresponding flags.go files

### ISSUE THREAD

**Issue by kcq** [docker-slim/docker-slim#252]
Example:

https://github.com/docker-slim/docker-slim/blob/master/pkg/app/master/commands/build/cli.go#L160

**Comment by mritunjaysharma394** [comment]
Hi @kcq , would love to work on this issue! Thanks!

**Comment by x-private-one** [comment]
> 

go for it :-)

**Comment by kcq** [comment]
> Hi @kcq , would love to work on this issue! Thanks!

go for it :-)
