### ISSUE TITLE
Console output as json with a flag to control when the console output is free form text and when it's json

### ISSUE THREAD

**Issue by kcq** [docker-slim/docker-slim#253]
Need to have a global flag to control the console output mode (`--json-output` or something like that).

**Comment by loganshamberger** [comment]
@kcq Could I take a stab at this?

**Comment by kcq** [comment]
Go for it @loganshamberger :) Let me know if you'd like to do a code walk through to learn about the execution context used for I/O and other things.

**Comment by loganshamberger** [comment]
@kcq I think that would be helpful. I've pulled it down and am just trying to get the code built and run to start.

**Comment by rghdrizzle** [comment]
@kcq is someone still working on this?

**Comment by kcq** [comment]
still open and still TBD :)

**Comment by akankshakumari393** [comment]
Hi @kcq is someone still working on it?

**Comment by kcq** [comment]
Are you interested in contributing this enhancement :)

**Comment by akankshakumari393** [comment]
@kcq yeah I am interested.

**Comment by kcq** [comment]
> @kcq yeah I am interested.

Let's chat then :)

**Comment by akankshakumari393** [comment]
hey @kcq, I am new to it, could you please suggest me where do we start with?

**Comment by kcq** [comment]
@akankshakumari393 when are you online? I can give you an overview.

A few notes to get you started in the meantime...

The docker-slim I/O happens using the `ExecutionContext` construct ( https://github.com/docker-slim/docker-slim/blob/master/pkg/app/execontext.go ). The`ExecutionContext.Output.Info()`, `ExecutionContext.Output.State()`, `ExecutionContext.Output.Message()` and `ExecutionContext.Output.Error()` calls are responsible for the actual console output and that's where we need to conditionally print using the standard formatting or json.

The docker-slim commands are here and that's where the ExecutionContext struct is used for I/O:
https://github.com/docker-slim/docker-slim/tree/master/pkg/app/master/commands

Example:
```
			xc.Out.Info("params",
				ovars{
					"target.type":   "image",
					"target":        targetRef,
					"continue.mode": continueAfter.Mode,
					"rt.as.user":    doRunTargetAsUser,
					"keep.perms":    doKeepPerms,
					"tags":          strings.Join(outputTags, ","),
				})
```
https://github.com/docker-slim/docker-slim/blob/master/pkg/app/master/commands/build/handler.go#L255

Also a couple of videos to watch:

https://www.youtube.com/watch?v=Y60g3Jz2Fg8&t=14s
https://www.youtube.com/watch?v=ioIG-oPg0pA&t=60s

**Comment by akankshakumari393** [comment]
Hey thanks, I will go through these and will let you know in case I have any doubt.

**Comment by akankshakumari393** [comment]
@kcq How is the globalflag `--log-format` different from the `json-output` that we are gonna add?

**Comment by kcq** [comment]
The `log-format` flag is for the logging data output. The standard output output data is different from the logging data, which is usually disabled and you enable it when you need additional debugging information. Both end up being printed to the screen, but they are independent of each other.

**Comment by kcq** [comment]
@akankshakumari393 let me know if you want to do an online session next week to go over the enhancements

**Comment by akankshakumari393** [comment]
@kcq I won't be available this week. I would be good if we can schedule it to next week.
