### ISSUE TITLE
Pass log level setting from the main app to the sensor

### ISSUE THREAD

**Issue by kcq** [docker-slim/docker-slim#254]
Right now the main app passes the debug flag to the sensor as a startup param when the global `--debug` flag is enabled. The `--debug` flag is a shortcut for the `debug` `log-level` configured with the `--log-level` global flag. 

We need to pass the log level param to the sensor when we configure the entrypoint/cmd fields for the temporary container.

**Comment by rikez** [comment]
Hey @kcq, I'd love to work on it. May I put a PR?

Do we also want to propagate the `log format`?

**Comment by kcq** [comment]
That'll be great @rikez ! Good idea with the log format too :)

**Comment by kcq** [comment]
thank you for making the enhancement @rikez ! let me know if you'd be interested in doing more and we'll find something interesting :)

**Comment by rikez** [comment]
@kcq no problem! yes, I'd like to help 💪 


* I haven't found any automated tests, is that right? Are there any plans to add them?
* I noticed there's a `deepsource.toml` file with the rules to run static analysis. Is it possible to run them locally? Do you think it would be useful to add a tool like [golangci-lint](https://github.com/golangci/golangci-lint)?

Let me know how I can help!

**Comment by kcq** [comment]
@rikez Need to update the static analysis tool setup... The current set of static checks are in `https://github.com/docker-slim/docker-slim/blob/master/scripts/src.inspect.sh`. Hoping to use `https://github.com/bwplotka/bingo` to have a consistent way to use the static analysis tools including `golangci-lint`. Was thinking about enabling these`golangci-lint` linters: govet, gosimple, staticcheck, ineffassign, errcheck, bodyclose, revive, gofmt, goconst, nakedret, dupl, gosec. `revive` will need extra tuning... Are you interested in spending cycles on enhancements like that?

The current goal with tests is to automate the e2e tests in `https://github.com/docker-slim/examples`. There's value in adding specialized unit tests for important or complicated packages (e.g., definitely a good idea to have a few unit tests for the package that reverse engineers Dockerfiles.

**Comment by rikez** [comment]
@kcq yes, I'd love to work on that improvement, but do you think this adds value atm? Is there anything else in the queue? a bug, a feature that you need help with? I'm down for that too.

I will create an issue for the linters, if there isn't one yet.

**Comment by kcq** [comment]
@rikez there's a lot todo definitely :) The linter enhancements will be nice if they quick wins. If you prefer functional enhancements then makes sense to focus there. A simple enhancement can be something like this one: https://github.com/docker-slim/docker-slim/issues/264 For more complicated enhancements adding support for compose in the `run` command can be good (no issue for it yet; there's the compose execution package that gets used in the `build` command and we'd need something similar for `run`). Adding support for container images with the `lint` command (also no issue yet; `lint` normally works by inspecting Dockerfiles and we need to make it work by inspecting containger images too... which will leverage the Dockerfile reverse engingeering capabilites we already have) For extra complicated enhancements figuring out why dev servers for node.js apps get stuck is a great enhancement.
