### ISSUE TITLE
Version 1.37.3 reports as outdated

### ISSUE THREAD

**Issue by goffinf** [docker-slim/docker-slim#257]
Expected Behavior
=================

No message indicating that the latest version (1.37.3) is outdated

---
Actual Behavior
=================

Outdated info message is output when running docker-slim

---
Steps to Reproduce the Problem
===============================

```
docker-slim version

...
cmd=version info=app version='linux|Transformer|1.37.3|97eb3c8c7f8c4e295a26c13882feb3f0539ab50f|2021-12-10_09:37:29AM' container=false dsimage=false
cmd=version info=app outdated=true current=1.37.2 verdict='your installed version is OUTDATED (local=1.37.3 current=1.37.2)'
...
```

---
Specifications
=================
  - Version: 1.37.3
  - Platform: Ubuntu 20.04.3 LTS

**Comment by kcq** [comment]
@goffinf thanks for opening the issue! great catch! It's a Lambda deployment bug where release deployment didn't quite deploy properly due to the recent AWS changes. The issue will be addressed in the next couple of days.

**Comment by goffinf** [comment]
@kcq no problem. I am happy to close now in anticipation of the fix, or equally ok if you want to close when you have that over the line ?

**Comment by kcq** [comment]
should be ok now
