### ISSUE TITLE
Dangling container after failing HTTP-probe app

### ISSUE THREAD

**Issue by Bohne9** [docker-slim/docker-slim#258]
Docker-Slim does not perform any cleanup after a failing HTTP-Probe app.

---

Right now, when using custom HTTP-Probe apps there is the issue that Docker-Slim simply exits after an HTTP-probe exec app fails. The consequence is that the container with the original image keeps running. Now you have to manually remove this container to be able to use Docker-Slim again since the ports are still bound.

However, this behaviour is especially critical when using Docker-Slim in a CI pipeline.

**Comment by kcq** [comment]
Thanks for opening the issue @Bohne9 ! Definitely shouldn't have any leftovers. Will have a fix soon.
