### ISSUE TITLE
Migrate the Main App from urfave/cli to urfave/cli/v2

### ISSUE THREAD

**Issue by kcq** [docker-slim/docker-slim#262]
The v2 has a number of nice features, but before we can take advantage of them we need to do a basic migration to the new version.

There's a nice migration guide:

https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md

**Comment by mritunjaysharma394** [comment]
Hey @kcq , I would like to work on this issue :)

**Comment by kcq** [comment]
> Hey @kcq , I would like to work on this issue :)

Go for it @mritunjaysharma394 :)
