### ISSUE TITLE
Add support for the HEALTHCHECK instruction when reverse engineering Dockerfiles

### ISSUE THREAD

**Issue by kcq** [docker-slim/docker-slim#264]
There's still no support for the HEALTHCHECK instruction:
https://github.com/docker-slim/docker-slim/blob/master/pkg/docker/dockerfile/reverse/reverse.go#L343

**Comment by mritunjaysharma394** [comment]
I think I can work on this @kcq :-)
Will try to look and create a PR hopefully

**Comment by kcq** [comment]
@mritunjaysharma394 great!
