### ISSUE TITLE
Optional / user defined ability to wait before starting each compose service

### ISSUE THREAD

**Issue by kcq** [docker-slim/docker-slim#268]
We need a flag (`compose-svc-start-wait` ) to control how long docker-slim should wait before starting each service when there's a compose file (`build`, `profile`, `run` commands though the `run` command doesn't have support for `compose` yet).

**Comment by Zachvice** [comment]
Hey @kcq I'd like to tackle this issue. I'm somewhat new to GO and docker-slim, could I get pointed in the right direction?

**Comment by kcq** [comment]
@Zachvice The [`Tour of Go`](https://go.dev/tour) and the two code walk through videos on [`Youtube`](https://www.youtube.com/channel/UCy7RHjJlaBhpCCbChrd8POA) are good resources. The [`code diagram`](https://app.codesee.io/maps/public/1cedd540-6451-11ec-a279-0572ca5abbdc) with CodeSee might be useful too.

Happy to do an intro code walk through too. Others might join as well if we do it.
