### ISSUE TITLE
Ability to override the container image when targeting compose service for minification (`--target-compose-svc-image` param)

### ISSUE THREAD

**Issue by kcq** [docker-slim/docker-slim#269]
You might have a compose file that doesn't reference the exact version of the container image you want to minified (e.g., the target service might reference the `latest` tag and you want to minify `v1.2.3` for your target image).

The `--target-compose-svc-image` command parameter (for `build` and `profile` commands) should provide a way to use the desired image version without having to rewrite your compose file. Need to use the value from the flag instead of the image field from the target service. 

This flag is relevant only when the `--target-compose-svc` and `--compose-file` parameters are.

**Comment by kcq** [comment]
@sreeo for for it :)

**Comment by mritunjaysharma394** [comment]
i think the above PR as fixed this issue, can we close this @kcq?

**Comment by kcq** [comment]
yes
