### ISSUE TITLE
creport.json no such file or directory

### ISSUE THREAD

**Issue by liuxiaopiao** [docker-slim/docker-slim#27]
Hi ,
When I used the docker-slim tool like this:
./docker-slim build --tag testslim myapp

It failed with below steps:
FATA[0138] docker-slim: failure                          error=stat /scratch/dockerfiles/slim/dist_linux/.images/cc1e574be08e894141e108356d70c592db7f85df9956170abb4aff8d22e50349/artifacts/creport.json: no such file or directory stack=/Users/me/Desktop/CI_GITHUB/docker-slim/_vendor/src/github.com/cloudimmunity/docker-slim/utils/errors.go:11 (0x561576)
/Users/me/Desktop/CI_GITHUB/docker-slim/_vendor/src/github.com/cloudimmunity/docker-slim/master/commands/build.go:120 (0x4aeacf)
/Users/me/Desktop/CI_GITHUB/docker-slim/apps/docker-slim/cli.go:321 (0x40b623)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x466dce)
/usr/local/go/src/reflect/value.go:432 (0x53fc4a)
/usr/local/go/src/reflect/value.go:300 (0x53e911)
/Users/me/Desktop/CI_GITHUB/docker-slim/_vendor/src/github.com/codegangsta/cli/app.go:483 (0x4bfcce)
/Users/me/Desktop/CI_GITHUB/docker-slim/_vendor/src/github.com/codegangsta/cli/command.go:186 (0x4c1c7f)
/Users/me/Desktop/CI_GITHUB/docker-slim/_vendor/src/github.com/codegangsta/cli/app.go:237 (0x4bd369)
/Users/me/Desktop/CI_GITHUB/docker-slim/apps/docker-slim/cli.go:526 (0x4063fb)
/Users/me/Desktop/CI_GITHUB/docker-slim/apps/docker-slim/main.go:5 (0x4064e9)
/usr/local/go/src/runtime/proc.go:111 (0x439140)
/usr/local/go/src/runtime/asm_amd64.s:1721 (0x469101)

Could you please help me on this? What's the root cause of it? And how can I resolve it?
Thank you very much!

**Comment by kcq** [comment]
This error happened because the creport.json isn't there. The report file isn't there if there was a failure analyzing the temporary container created for the target Docker image. What's there before the error? Also a good idea to take a look at the logs for the temporary container. You should find the container if you do "docker ps -a".

**Comment by kcq** [comment]
The latest release (1.18) mitigates this condition, so docker-slim will not fail with an exception. However, there's a reason why the report file isn't generated and that's a separate issue (need to see the container log to know more). Please reopen if you still have the problem and please add the container logs as well (by running docker-slim in the debug mode).
