### ISSUE TITLE
Using Docker-slim on remote host

### ISSUE THREAD

**Issue by pedroricardo** [docker-slim/docker-slim#270]
Currently I use docker-compose v2 with the --context flag which makes it possible for me to build and launch a container on a remote host.

I would like to know if there is any possibility of using docker-slim under these conditions, with docker-compose --context

**Comment by kcq** [comment]
The `--host`, `--tls`, `--tls-verify` and `--tls-cert-path` global flags in `docker-slim` should allow you to do that (you can use the DOCKER_HOST env var too). It should give you the same results with a bit of extra work and without a nice named context to select your remote docker daemon. This is how `docker-slim` is able to run on Gitlab with their docker runners, for example.

**Comment by pedroricardo** [comment]
I get it, so the docker flags are compatible! it helps

but in relation to composefile is there any way to use my docker-compose.yml built in to docker-slim to build smaller containers using just the docker-compose up --build command in the terminal

**Comment by kcq** [comment]
invoking `docker-slim` when you run `docker-compose up --build` is tricky because `docker-compose` doesn't support plugins where 3rd party components can be integrated.
