### ISSUE TITLE
Not working in docker 1.12

### ISSUE THREAD

**Issue by pvm-uf** [docker-slim/docker-slim#28]
In docker 1.12 (1.12.0-rc4-beta19 (build: 10258)) the API has changed and building image with docker-slim now generates error:

FATA[0000] docker-slim: failure                          error=API error (400): {"message":"starting container with HostConfig was deprecated since v1.10 and removed in v1.12"}

Are there any plans to support this version of docker?

**Comment by kcq** [comment]
Absolutely! Thanks for the report! It should be ready by the time there's an official 1.12 release.

**Comment by kcq** [comment]
Should be resolved by the latest release: https://github.com/docker-slim/docker-slim/releases/tag/1.16
