### ISSUE TITLE
How to get pass USER INPUT REQUIRED when using --http-probe=false?

### ISSUE THREAD

**Issue by Snazzie** [docker-slim/docker-slim#338]
When using `--http-probe=false` with build, cmd waits for user input before continuing. This behaviour blocks CD pipelines, how does one get passed this?  

Expected Behavior
=================

Doesnt require user input to continue

---
Actual Behavior
=================

Requires user input to continue

---
Steps to Reproduce the Problem
===============================
 

  1.
  1.
  1.

---
Specifications
=================
  - Version:
  - Platform:

**Comment by kcq** [comment]
Probably the easiest option to use the timeout option for the `--continue-after` flag where you specify the number of seconds to wait (to allow the sensor to collect enough information about your app) before finishing its processing. Can you share a bit more about your containerized application? What kind of app is it? What's the language?

**Comment by Snazzie** [comment]
Figured it out.

In your documentation

>When docker-slim runs it gives you an opportunity to interact with the temporary container it creates. By default, it will pause and wait for your input before it continues its execution. You can change this behavior using the --continue-after flag.

I got passed it by providing `--continue-after exec --exec "echo hello" `

**Comment by Snazzie** [comment]
>where you specify the number of seconds to wait (to allow the sensor to collect enough information about your app) 

My app doesnt expose any ports :^)

funnily, i attempted `--continue-after 4` without `--http-probe false` and it failed on the probing part and i didnt think to try it with the http-probe flag. 

I just tried it with `--http-probe false --continue-after 4` and it did proceed after 4 seconds
