### ISSUE TITLE
Missing make target in README for containerized build

### ISSUE THREAD

**Issue by akankshakumari393** [docker-slim/docker-slim#347]
Description
===============
In the README, we are currently not providing proper make target for containerized build. [https://github.com/docker-slim/docker-slim/blob/b5d7fe290e94236657021a15d36fdbdd5d690107/README.md?plain=1#L898](https://github.com/docker-slim/docker-slim/blob/b5d7fe290e94236657021a15d36fdbdd5d690107/README.md?plain=1#L898)

Expected Behavior
=================
we should provide build target

---
Actual Behavior
=================

---
Steps to Reproduce the Problem
===============================
 

  1.
  1.
  1.

---
Specifications
=================
  - Version:
  - Platform:

**Comment by kcq** [comment]
yes, good idea

**Comment by akankshakumari393** [comment]
cool, I will raise a PR for this

**Comment by mritunjaysharma394** [comment]
I think this issue is fixed, we can close it @kcq ?
