### ISSUE TITLE
Incorrect env value 

### ISSUE THREAD

**Issue by jevi061** [docker-slim/docker-slim#358]
Expected Behavior
=================

env variables in slim image are the same as target image 

---
Actual Behavior
=================

env values in slim image are incorrect
**Target Image:** 
```shell
ENV JAVA_OPTS=-server -Xms512m -Xmx1024m -XX:MetaspaceSize=256m -XX:MaxspaceSize=512m
````
**Slim Image:** 
```shell
ENV JAVA_OPTS=-server -Xms512m -Xmx1024m -XX:MetaspaceSize
````

---
Steps to Reproduce the Problem
===============================
 

  1. build any docker image with env like above.
  2. build slim image with target image generated in last step.
  3. inspect env of this two images,

---
Specifications
=================
  - Version:  1.37.6
  - Platform: CentOS Linux 7

**Comment by kcq** [comment]
thanks for opening the issue @jevi061! just to double check... what do you get if you put the env var value in quotes like this `ENV JAVA_OPTS="-server -Xms512m -Xmx1024m -XX:MetaspaceSize=256m -XX:MaxspaceSize=512m"`

**Comment by mritunjaysharma394** [comment]
Thanks @jevi061 for opening the issue, upon initial investigation, I think this is because we are not handling cases of more than 1 `=` in ENV. The below line of code can tell this to some extent and that's why we get only after the first `=` in slim image  `ENV JAVA_OPTS=-server -Xms512m -Xmx1024m -XX:MetaspaceSize`: 

If this hypothesis is correct, I can start working on PR to fix this may be? cc @kcq 
https://github.com/docker-slim/docker-slim/blob/97416477da7e6684fc555c2a581f3dcb217c36b0/pkg/app/master/builder/image_builder.go#L330

**Comment by mritunjaysharma394** [comment]
Or may be this part of the code where the issue might be: https://github.com/docker-slim/docker-slim/blob/97416477da7e6684fc555c2a581f3dcb217c36b0/pkg/docker/dockerfile/dockerfile.go#L86

**Comment by jevi061** [comment]
@mritunjaysharma394 Thanks for your quick reply!

**Comment by jevi061** [comment]
> thanks for opening the issue @jevi061! just to double check... what do you get if you put the env var value in quotes like this `ENV JAVA_OPTS="-server -Xms512m -Xmx1024m -XX:MetaspaceSize=256m -XX:MaxspaceSize=512m"`

@kcq its not about the quotes, and @mritunjaysharma394 made a pr which could fix this , so I will close this issue

**Comment by kcq** [comment]
@jevi061 by the way, the spec ( https://docs.docker.com/engine/reference/builder/#env ) requires that the white spaces are escaped:

```
MY_NAME="John Doe"
ENV MY_DOG=Rex\ The\ Dog
ENV MY_CAT=fluffy
```

It also has this interesting part:

```The ENV instruction allows for multiple <key>=<value> ... variables to be set at one time, and the example below will yield the same net results in the final image:

ENV MY_NAME="John Doe" MY_DOG=Rex\ The\ Dog \
    MY_CAT=fluffy
```

That means that your `ENV JAVA_OPTS=-server -Xms512m -Xmx1024m -XX:MetaspaceSize=256m -XX:MaxspaceSize=512m` might be interpreted as in an unexpected way.

They also mention the legacy `ENV MY_VAR my-value` format, which might be better in your case.

This isn't directly related to the bug, but i thought i'd mention it :)
