### ISSUE TITLE
Tag 1.17

### ISSUE THREAD

**Issue by sgerrand** [docker-slim/docker-slim#38]
The last tag in this repository is v1.13, but the latest release is v1.17. Would you please tag v1.17 from the appropriate commit. This will help packagers immensely. 😸

**Comment by kcq** [comment]
The tag names changed from v<version> to just <version>. There should be a tag named '1.17'. Need to do a bit of cleanup there. Sorry about the confusion!

**Comment by kcq** [comment]
All tags should have the same format now ([version]). You'll need to run `git pull --prune --tags` on your existing cloned repo (or you can do a fresh clone :-)).

**Comment by kcq** [comment]
Let me know if you have any problems.
