### ISSUE TITLE
GitHub: offer .tar.gz binary downloads - not just .zip

### ISSUE THREAD

**Issue by Nowaker** [docker-slim/docker-slim#42]
https://github.com/docker-slim/docker-slim/releases

Two reasons:

1. Every Linux comes with `tar` - but not `unzip`.
2. ZIP format doesn't carry a +x flag for binaries. `chmod +x` is needed after `unzip`.

**Comment by kcq** [comment]
That's a great idea! Thank you! Will do this ASAP. 

There's also a wishlist item to publish docker-slim to the major package repositories. If this is something you are interested in doing your contribution will be greatly appreciated!

**Comment by Nowaker** [comment]
I can submit to AUR (Arch User Repository).

**Comment by kcq** [comment]
That would be great if you can help out with that!

**Comment by kcq** [comment]
By the way, the latest release should have a tar.gz download too.

**Comment by ulgens** [comment]
It seems fixed.
