### ISSUE TITLE
docker-slim can not generate slim container

### ISSUE THREAD

**Issue by thatsk** [docker-slim/docker-slim#51]
'''Dockerfile:-
FROM centos
LABEL maintainer="thatsk"
RUN yum install epel-release wget tar unzip ruby ruby-devel gcc make sudo -y
RUN echo 'puppet    ALL=(ALL)       NOPASSWD:ALL' >> /etc/sudoers
RUN gem install r10k fpm
RUN groupadd -g 52 puppet && useradd -ms /bin/bash -u 52 -g 52 puppet  && mkdir -p /home/puppet/.ssh
ADD puppetssh/ /home/puppet/.ssh
ADD r10k.yaml /etc/puppetlabs/r10k/
RUN  mkdir -p /var/lib/r10k/cache /etc/puppetlabs/code /etc/puppetlabs/r10k /etc/puppetlabs/code/reference & chown -R puppet:puppet /home/puppet/.ssh && chown -R puppet:puppet /etc/puppetlabs/r10k && chown -R puppet:puppet /var/lib/r10k && chown -R puppet:puppet /etc/puppetlabs/code
#Optimizing Docker Size image
RUN rm -rf \
        /usr/share/man/* \
        /usr/include/* \
        /usr/share/doc/* \
        /usr/share/emacs/* \
        /usr/share/xemacs/* \
        /usr/share/vim/* \
        /usr/share/gettext/* \
        /usr/share/gettext-0.19.8/* \
        /usr/share/zoneinfo/* \
        /usr/share/zsh/*
#setting up user password
RUN echo "root:e0rtv12" | chpasswd
RUN echo "puppet:puppet" | chpasswd
#ADDING pulp extension
RUN yum install rpm-build java-1.8.0-openjdk-devel -y && mkdir /home/puppet/.pulp && wget -O /etc/yum.repos.d/rhel-pulp.repo https://repos.fedorapeople.org/repos/pulp/pulp/rhel-pulp.repo && yum groupinstall Development tools -y && yum install pulp-docker-admin-extensions pulp-python-admin-extensions pulp-admin-client pulp-rpm-admin-extensions pulp-puppet-admin-extensions -y
#Adding pulp server information
ADD pulp/admin.conf /home/puppet/.pulp/admin.conf
RUN mkdir -p /isilon/devops/puppetlabs &&  chown -R puppet:puppet /etc/puppetlabs/
USER puppet
RUN sudo ln -s /etc/puppetlabs/code /isilon/devops/puppetlabs/code
RUN sudo chown -R puppet:puppet /home/puppet/.pulp & sudo chmod -R 0700 /home/puppet/.pulp
ENV HOME /home/puppet
WORKDIR $HOME

Go Version:-
go version go1.10.1 linux/amd64
Centos:-
CentOS Linux release 7.4.1708 (Core)
Docker Slim version:-
docker-slim --version
2018/04/25 13:24:14 Couldn't set key CPE_NAME, no corresponding struct field found
2018/04/25 13:24:14 Couldn't set key , no corresponding struct field found
2018/04/25 13:24:14 Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
2018/04/25 13:24:14 Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
2018/04/25 13:24:14 Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
2018/04/25 13:24:14 Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
2018/04/25 13:24:14 Couldn't set key , no corresponding struct field found
docker-slim version linux|Tetra|1.20|f79fefbb88486f9431fdae5c6f65155fb7b3d39b|2018-03-05_05:20:22AM (go1.10)

Container:-
r10k                                                  latest              5daf0cc38ce5        14 minutes ago      949MB

Full Docker-slim logs:-
 docker-slim build --http-probe --show-clogs r10k
2018/04/25 13:37:25 Couldn't set key CPE_NAME, no corresponding struct field found
2018/04/25 13:37:25 Couldn't set key , no corresponding struct field found
2018/04/25 13:37:25 Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
2018/04/25 13:37:25 Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
2018/04/25 13:37:25 Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
2018/04/25 13:37:25 Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
2018/04/25 13:37:25 Couldn't set key , no corresponding struct field found
docker-slim[build]: state=started
docker-slim[build]: info=params target=r10k continue.mode=enter
docker-slim[build]: state=inspecting.image
docker-slim[build]: info=image id=sha256:5daf0cc38ce5f26fe56ed41ac4e13d45a49f9f20a7b5552cf5ee5a6d375df9b4 size.bytes=949049028 size.human=949 MB
docker-slim[build]: state=inspecting.container
docker-slim[build]: info=prompt message='press <enter> when you are done using the container'

docker-slim[build]: state=http.probe.starting
docker-slim[build]: state=http.probe.done
docker-slim: container stdout:
docker-slim: container stderr:
2018/04/25 13:37:26 Couldn't set key CPE_NAME, no corresponding struct field found
2018/04/25 13:37:26 Couldn't set key , no corresponding struct field found
2018/04/25 13:37:26 Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
2018/04/25 13:37:26 Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
2018/04/25 13:37:26 Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
2018/04/25 13:37:26 Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
2018/04/25 13:37:26 Couldn't set key , no corresponding struct field found
time="2018-04-25T13:37:26Z" level=info msg="sensor: args => []string{"/opt/dockerslim/bin/sensor"}"
time="2018-04-25T13:37:26Z" level=info msg="sensor: creating event publisher..."
time="2018-04-25T13:37:26Z" level=info msg="sensor: creating cmd server..."
time="2018-04-25T13:37:26Z" level=info msg="sensor: waiting for commands..."
time="2018-04-25T13:37:26Z" level=info msg="sensor: monitor starting..."
time="2018-04-25T13:37:26Z" level=info msg="fanmon: Run"
time="2018-04-25T13:37:26Z" level=fatal msg="docker-slim: failure" error="operation not permitted" stack="goroutine 1 [running]:
runtime/debug.Stack(0xffffffffffffffff, 0x1, 0x5d7320)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/docker-slim/docker-slim/pkg/utils/errutils.FailOn(0x5d7320, 0xc420024120)
        /Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/pkg/utils/errutils/errutils.go:14 +0x51
github.com/docker-slim/docker-slim/internal/app/sensor/monitors/fanotify.Run(0x5b61fa, 0x1, 0xc4200f4060, 0x12)
        /Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/sensor/monitors/fanotify/monitor.go:38 +0x8f
github.com/docker-slim/docker-slim/internal/app/sensor.monitor(0xc42005a070, 0xc420062660, 0xc420060360, 0xc42005a0e0, 0xc4200e8420, 0xc42006e7b0, 0xc)
        /Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/sensor/app.go:47 +0x122
github.com/docker-slim/docker-slim/internal/app/sensor.Run()
        /Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/sensor/app.go:130 +0x4ec
main.main()
        /Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/cmd/docker-slim-sensor/main.go:8 +0x20
" version="linux|Tetra|latest|latest|latest (go1.10)"
docker-slim: end of container logs =============
docker-slim[build]: state=processing
docker-slim: Fat image - Dockerfile instructures: start ====
new image
ADD file:f755805244a649eccae3a3e63be291048deeb23e1c5a500d2f92b4eedc452322 in /
 LABEL org.label-schema.schema-version== 1.0     org.label-schema.name=CentOS Base Image     org.label-schema.vendor=CentOS     org.label-schema.license=GPLv2     org.label-schema.build-date=20180402
 CMD ["/bin/bash"]
end of image: centos (id: sha256:e934aafc22064b7322c0250f1e32e5ce93b2d19b356f4537f5864bd102e8531f tags: latest)

new image
 LABEL maintainer=thatsk
RUN yum install epel-release wget tar unzip ruby ruby-devel gcc make sudo -y
RUN echo 'puppet    ALL=(ALL)       NOPASSWD:ALL' >> /etc/sudoers
RUN gem install r10k fpm
RUN groupadd -g 52 puppet && \
        useradd -ms /bin/bash -u 52 -g 52 puppet && \
        mkdir -p /home/puppet/.ssh
ADD dir:1576b0b81797e6ee72d158d2fa1a6bcec8e10bc723312afb9c5acd7eb4c4acc5 in /home/puppet/.ssh
ADD file:9176ccd326f4776d9972d4033da634a200a5559785308a443b3fce8e81be6af0 in /etc/puppetlabs/r10k/
RUN mkdir -p /var/lib/r10k/cache /etc/puppetlabs/code /etc/puppetlabs/r10k /etc/puppetlabs/code/reference & chown -R puppet:puppet /home/puppet/.ssh && \
        chown -R puppet:puppet /etc/puppetlabs/r10k && \
        chown -R puppet:puppet /var/lib/r10k && \
        chown -R puppet:puppet /etc/puppetlabs/code
RUN rm -rf      /usr/share/man/*        /usr/include/*  /usr/share/doc/*        /usr/share/emacs/*      /usr/share/xemacs/* /usr/share/vim/*         /usr/share/gettext/*    /usr/share/gettext-0.19.8/*     /usr/share/zoneinfo/*   /usr/share/zsh/*
RUN echo "root:e0rtv12" | chpasswd
RUN echo "puppet:puppet" | chpasswd
RUN yum install rpm-build java-1.8.0-openjdk-devel -y && \
        mkdir /home/puppet/.pulp && \
        wget -O /etc/yum.repos.d/rhel-pulp.repo https://repos.fedorapeople.org/repos/pulp/pulp/rhel-pulp.repo && \
        yum groupinstall Development tools -y && \
        yum install pulp-docker-admin-extensions pulp-python-admin-extensions pulp-admin-client pulp-rpm-admin-extensions pulp-puppet-admin-extensions -y
ADD file:0c170c80ffcc43e2be6f62a8722194c38d8574922f88eb12c33deee37eb538e3 in /home/puppet/.pulp/admin.conf
RUN mkdir -p /isilon/devops/puppetlabs && \
        chown -R puppet:puppet /etc/puppetlabs/
 USER puppet
RUN sudo ln -s /etc/puppetlabs/code /isilon/devops/puppetlabs/code
RUN sudo chown -R puppet:puppet /home/puppet/.pulp & sudo chmod -R 0700 /home/puppet/.pulp
 ENV HOME=/home/puppet
WORKDIR /home/puppet
end of image: r10k (id: sha256:5daf0cc38ce5f26fe56ed41ac4e13d45a49f9f20a7b5552cf5ee5a6d375df9b4 tags: latest)

docker-slim: Fat image - Dockerfile instructures: end ======
docker-slim[build]: info=results status='no data collected (no minified image generated). (version: linux|Tetra|1.20|f79fefbb88486f9431fdae5c6f65155fb7b3d39b|2018-03-05_05:20:22AM (go1.10))'
docker-slim[build]: state=exited

focused error:-
**time="2018-04-25T13:37:26Z" level=fatal msg="docker-slim: failure" error="operation not permitted" stack="goroutine 1 [running]:
runtime/debug.Stack(0xffffffffffffffff, 0x1, 0x5d7320)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/docker-slim/docker-slim/pkg/utils/errutils.FailOn(0x5d7320, 0xc420024120)
        /Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/pkg/utils/errutils/errutils.go:14 +0x51
github.com/docker-slim/docker-slim/internal/app/sensor/monitors/fanotify.Run(0x5b61fa, 0x1, 0xc4200f4060, 0x12)
        /Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/sensor/monitors/fanotify/monitor.go:38 +0x8f
github.com/docker-slim/docker-slim/internal/app/sensor.monitor(0xc42005a070, 0xc420062660, 0xc420060360, 0xc42005a0e0, 0xc4200e8420, 0xc42006e7b0, 0xc)
        /Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/sensor/app.go:47 +0x122
github.com/docker-slim/docker-slim/internal/app/sensor.Run()
        /Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/sensor/app.go:130 +0x4ec
main.main()
        /Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/cmd/docker-slim-sensor/main.go:8 +0x20
" version="linux|Tetra|latest|latest|latest (go1.10)"
docker-slim: end of container logs =============**

**Comment by thatsk** [comment]
is there any installtion problem?

**Comment by thatsk** [comment]
I have tried your example. but it generates 0bytes.
docker-slim --version
2018/04/25 13:52:06 Couldn't set key CPE_NAME, no corresponding struct field found
2018/04/25 13:52:06 Couldn't set key , no corresponding struct field found
2018/04/25 13:52:06 Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
2018/04/25 13:52:06 Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
2018/04/25 13:52:06 Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
2018/04/25 13:52:06 Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
2018/04/25 13:52:06 Couldn't set key , no corresponding struct field found
docker-slim version linux|Tetra|1.20|f79fefbb88486f9431fdae5c6f65155fb7b3d39b|2018-03-05_05:20:22AM (go1.10)
root@kunal.infra.sre.smf1.mobitv: ~# docker-slim build --http-probe my/sample-node-app
2018/04/25 13:52:32 Couldn't set key CPE_NAME, no corresponding struct field found
2018/04/25 13:52:32 Couldn't set key , no corresponding struct field found
2018/04/25 13:52:32 Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
2018/04/25 13:52:32 Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
2018/04/25 13:52:32 Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
2018/04/25 13:52:32 Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
2018/04/25 13:52:32 Couldn't set key , no corresponding struct field found
docker-slim[build]: state=started
docker-slim[build]: info=params target=my/sample-node-app continue.mode=enter
docker-slim[build]: state=inspecting.image
docker-slim[build]: info=image id=sha256:7de201e4917ec4615b1b61eb2cffe242859e023224fbaa29d684b32f424cccbe size.bytes=453658867 size.human=454 MB
docker-slim[build]: state=inspecting.container
docker-slim[build]: info=prompt message='press <enter> when you are done using the container'

docker-slim[build]: state=processing
docker-slim[build]: state=building message='building minified image'
docker-slim[build]: state=completed
docker-slim[build]: info=results status='MINIFIED BY +InfX [453658867 (454 MB) => 0 (0 B)]'
docker-slim[build]: info=results  image.name=my/sample-node-app.slim image.size='0 B' data=false
docker-slim[build]: info=results  artifacts.location='/usr/local/bin/.images/7de201e4917ec4615b1b61eb2cffe242859e023224fbaa29d684b32f424cccbe/artifacts'
docker-slim[build]: info=results  artifacts.report=creport.json
docker-slim[build]: info=results  artifacts.dockerfile.original=Dockerfile.fat
docker-slim[build]: info=results  artifacts.dockerfile.new=Dockerfile
docker-slim[build]: info=results  artifacts.seccomp=my-sample-node-app-seccomp.json
docker-slim[build]: info=results  artifacts.apparmor=my-sample-node-app-apparmor-profile
docker-slim[build]: state=done

**Comment by thatsk** [comment]
your example also not working properly on centos based system. Please check.

**Comment by thatsk** [comment]
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:09:15 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:13:03 2018
  OS/Arch:      linux/amd64
  Experimental: false

**Comment by thatsk** [comment]
if you need any more information from me please let me know

**Comment by Kenith** [comment]
same issue here

**Comment by Kenith** [comment]
wangchengs-MacBook-Pro:ta-visual-lib wangcheng$ sudo docker-slim build --http-probe consol/centos-xfce-vnc
Password:
docker-slim[build]: state=started
docker-slim[build]: info=params target=consol/centos-xfce-vnc continue.mode=enter
docker-slim[build]: state=inspecting.image
docker-slim[build]: info=image id=sha256:30a575827da37c6206f135050db80c10b863a078ebae24db6680d0eac4127438 size.bytes=1493641684 size.human=1.5 GB
docker-slim[build]: state=inspecting.container
docker-slim[build]: info=prompt message='press <enter> when you are done using the container'
docker-slim[build]: state=http.probe.starting
docker-slim[build]: state=http.probe.done







docker-slim: container stdout:
docker-slim: container stderr:
2018/05/20 04:44:33 Couldn't set key CPE_NAME, no corresponding struct field found
2018/05/20 04:44:33 Couldn't set key , no corresponding struct field found
2018/05/20 04:44:33 Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
2018/05/20 04:44:33 Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
2018/05/20 04:44:33 Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
2018/05/20 04:44:33 Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
2018/05/20 04:44:33 Couldn't set key , no corresponding struct field found
time="2018-05-20T04:44:33Z" level=info msg="sensor: args => []string{"/opt/dockerslim/bin/sensor"}"
time="2018-05-20T04:44:33Z" level=info msg="sensor: creating event publisher..."
time="2018-05-20T04:44:33Z" level=info msg="sensor: creating cmd server..."
time="2018-05-20T04:44:33Z" level=info msg="sensor: waiting for commands..."
time="2018-05-20T04:44:33Z" level=info msg="sensor: monitor starting..."
time="2018-05-20T04:44:33Z" level=info msg="fanmon: Run"
time="2018-05-20T04:44:33Z" level=fatal msg="docker-slim: failure" error="operation not permitted" stack="goroutine 1 [running]:
runtime/debug.Stack(0xffffffffffffffff, 0x1, 0x5d7320)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/docker-slim/docker-slim/pkg/utils/errutils.FailOn(0x5d7320, 0xc42006c0e8)
	/Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/pkg/utils/errutils/errutils.go:14 +0x51
github.com/docker-slim/docker-slim/internal/app/sensor/monitors/fanotify.Run(0x5b61fa, 0x1, 0xc42005e360, 0x1)
	/Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/sensor/monitors/fanotify/monitor.go:38 +0x8f
github.com/docker-slim/docker-slim/internal/app/sensor.monitor(0xc4201d0000, 0xc42005e2a0, 0xc4201c2180, 0xc4201d0070, 0xc4200544e0, 0xc4200179e0, 0x9)
	/Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/sensor/app.go:47 +0x122
github.com/docker-slim/docker-slim/internal/app/sensor.Run()
	/Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/sensor/app.go:130 +0x4ec
main.main()
	/Users/q/Desktop/ALL_DSLIM/BUG_DS_ISSUE_44/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/cmd/docker-slim-sensor/main.go:8 +0x20
" version="linux|Tetra|latest|latest|latest (go1.10)"
docker-slim: end of container logs =============
docker-slim[build]: state=processing
docker-slim: Fat image - Dockerfile instructures: start ====
# new image
ADD file:8d83f3e2c14f39e7f7b281117a45e245c1941668f2d560e9f7ac23da89d667a9 in /
 LABEL name=CentOS Base Image vendor=CentOS license=GPLv2 build-date=20180302
 CMD ["/bin/bash"]
 MAINTAINER Tobias Schneck "tobias.schneck@consol.de"
 ENV REFRESHED_AT=2018-03-27
 LABEL io.k8s.description=Headless VNC Container with Xfce window manager, firefox and chromium io.k8s.display-name=Headless VNC Container based on Centos io.openshift.expose-services=6901:http,5901:xvnc io.openshift.tags=vnc, centos, xfce io.openshift.non-scalable=true
 ENV DISPLAY=:1 VNC_PORT=5901 NO_VNC_PORT=6901
 EXPOSE 5901/tcp 6901/tcp
 ENV HOME=/headless TERM=xterm STARTUPDIR=/dockerstartup INST_SCRIPTS=/headless/install NO_VNC_HOME=/headless/noVNC VNC_COL_DEPTH=24 VNC_RESOLUTION=1280x1024 VNC_PW=vncpassword VNC_VIEW_ONLY=false
WORKDIR /headless
ADD dir:0c208c0e80ba40329e3e9492e340a15e736389a11f6b5ebdfacf10fe1cd8789f in /headless/install/
ADD dir:5dec200fdd600490ab5b43551a66aec04cd729b340026945755d3d28c7decf3e in /headless/install/
RUN find $INST_SCRIPTS -name '*.sh' -exec chmod a+x {} +
RUN $INST_SCRIPTS/tools.sh
 ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
RUN $INST_SCRIPTS/tigervnc.sh
RUN $INST_SCRIPTS/no_vnc.sh
RUN $INST_SCRIPTS/firefox.sh
RUN $INST_SCRIPTS/chrome.sh
RUN $INST_SCRIPTS/xfce_ui.sh
ADD dir:b83656f2f17ede3d3d90f30212122d7cec5acea63a58eb04212601ef961d573f in /headless/
RUN $INST_SCRIPTS/libnss_wrapper.sh
ADD dir:5d8b54f96a132379534c6d5e611ac607d2cf12cb808e8d6f567ef711a871a91b in /dockerstartup
RUN $INST_SCRIPTS/set_user_permission.sh $STARTUPDIR $HOME
 USER [1000]
 ENTRYPOINT ["/dockerstartup/vnc_startup.sh"]
 CMD ["--wait"]
# end of image: consol/centos-xfce-vnc (id: sha256:30a575827da37c6206f135050db80c10b863a078ebae24db6680d0eac4127438 tags: latest)

docker-slim: Fat image - Dockerfile instructures: end ======
docker-slim[build]: info=results status='no data collected (no minified image generated). (version: darwin|Tetra|1.20|f79fefbb88486f9431fdae5c6f65155fb7b3d39b|2018-03-05_05:20:22AM (go1.10))'
docker-slim[build]: state=exited

**Comment by Kenith** [comment]
not supported the centos, and it is mentioned in readme:
**docker-slim has been used with Node.js, Python, Ruby, Java, Golang and PHP running on Ubuntu, Debian and Alpine Linux.**

**Comment by thatsk** [comment]
Docker-slim is installed on centos is it okay ? Then i am trying to build alpine based container which is of sized 267 MB. After build its shows 0Bytes. I have used your example of alpinego but got the same result.
Looks like you are trying to say that docker-slim has to be installed on mac of debian based system. And you are only able to build those images those are shown in readme. 


Sending build context to Docker daemon  673.8kB
Step 1/1 : FROM golang:alpine
alpine: Pulling from library/golang
ff3a5c916c92: Already exists
1a649ea86bca: Already exists
ce35f4d5f86a: Already exists
7db6b75ae47d: Pull complete
fc46bec5ec29: Pull complete
Digest: sha256:9de80ce12179b571ed46f9d1fb12261640a6d5af04689d6536a07f9dc23eae50
Status: Downloaded newer image for golang:alpine
 ---> 05fe62871090
Successfully built 05fe62871090
Successfully tagged alpinego:latest
root@kunal.infra.sre.smf1.mobitv: ~/docker/mobi-docker# docker-slim build --http-probe alpinego:latest
2018/05/21 03:25:53 Couldn't set key CPE_NAME, no corresponding struct field found
2018/05/21 03:25:53 Couldn't set key , no corresponding struct field found
2018/05/21 03:25:53 Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
2018/05/21 03:25:53 Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
2018/05/21 03:25:53 Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
2018/05/21 03:25:53 Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
2018/05/21 03:25:53 Couldn't set key , no corresponding struct field found
docker-slim[build]: state=started
docker-slim[build]: info=params target=alpinego:latest continue.mode=enter
docker-slim[build]: state=inspecting.image
docker-slim[build]: info=image id=sha256:05fe62871090f69071a42563d90ea9cc8e392a4d78b5c73dd7a0bc8410fcc79f size.bytes=375644187 size.human=376 MB
docker-slim[build]: state=inspecting.container
docker-slim[build]: info=prompt message='press <enter> when you are done using the container'

docker-slim[build]: state=processing
docker-slim[build]: state=building message='building minified image'
docker-slim[build]: state=completed
docker-slim[build]: state=http.probe.starting
docker-slim[build]: state=http.probe.done
docker-slim[build]: info=results status='MINIFIED BY +InfX [375644187 (376 MB) => 0 (0 B)]'
docker-slim[build]: info=results  image.name=alpinego.slim image.size='0 B' data=false
docker-slim[build]: info=results  artifacts.location='/usr/local/bin/.images/05fe62871090f69071a42563d90ea9cc8e392a4d78b5c73dd7a0bc8410fcc79f/artifacts'
docker-slim[build]: info=results  artifacts.report=creport.json
docker-slim[build]: info=results  artifacts.dockerfile.original=Dockerfile.fat
docker-slim[build]: info=results  artifacts.dockerfile.new=Dockerfile
docker-slim[build]: info=results  artifacts.seccomp=alpinego-seccomp.json
docker-slim[build]: info=results  artifacts.apparmor=alpinego-apparmor-profile
docker-slim[build]: state=done


It's Awesome if you can support redhat based derivatives

**Comment by kcq** [comment]
Thank you guys for trying it with Centos. I really appreciate that you took the time to report these bugs! Looks like there might be a couple of host and container related issues. One of the problems appears to be related to how Fanotify works on Centos. It'll be great to repro the errors. @thatsk what version of Centos did you use for your host OS when you tried to minify the Alpine Go example?

**Comment by kcq** [comment]
@thatsk The new 1.24 release ( https://github.com/docker-slim/docker-slim/releases/tag/1.24 ) added support for CentOS images and support for non-default users, which is what you had in your original snippet you shared (puppet). Can you give it a try to see how it works for your images?

**Comment by kcq** [comment]
Closing it for now... Please reopen if you still see the same problem.
