### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by maxmcd** [docker-slim/docker-slim#53]
Can a common license be added to this project?

**Comment by kcq** [comment]
Didn't want to impose any restrictions. What kind of license would you like to see?

**Comment by maxmcd** [comment]
As far I know a lack of specific license terms doesn't mean one can freely use the code. https://choosealicense.com/no-permission/

MIT or Apache 2?

**Comment by maxmcd** [comment]
Totally! Saw that when initially looking through the repo 😄

Couldn't find any terms for a hacker license in searching online, is there a reference somewhere?

**Comment by kcq** [comment]
It's a 'do whatever you want' license :-) To make it less confusing I made it Apache 2.
