### ISSUE TITLE
Base CentOS images error: "no such file or directory"

### ISSUE THREAD

**Issue by Zebreu** [docker-slim/docker-slim#55]
Hi, I've ran into an issue after running "docker-slim build centos" (using the official latest image from Docker Hub). Once minified, the centos.slim image can't be executed:

docker run centos.slim:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.

docker run -it centos.slim bash:
standard_init_linux.go:190: exec user process caused "no such file or directory"

Is this a known issue that I simply couldn't find mentioned?

Thanks!

**Comment by Zebreu** [comment]
Oh, sorry, I was sharing the simplest example possible. I have a large Python application running on top of it where it also produces the same error. It also happens if you simply run a Python hello world script.

**Comment by kcq** [comment]
Can you share more about your python app design and how it's started. How do you run the app in your container? Is there a wrapper shell script? What does that script do? Are there multiple processes?

In the meantime, I'll add a CentOS version for the sample apps.

**Comment by Zebreu** [comment]
The app itself seems irrelevant, because just having the container do something like 
RUN ["python", "hello_world.py"] 
(where hello_world.py is just a print statement) reproduced the error on my end, on Ubuntu 14.04 and 18.04.
The larger app had nothing fancy (single threaded/process, no wrapper, executes one script with the python interpreter and terminates once it's done) so that's why I tried a simple hello world example to share.

**Comment by kcq** [comment]
Thanks for the extra info! Super useful! What version of Python did you use for the test app?

**Comment by Zebreu** [comment]
Python 3.6 I believe.

**Comment by kcq** [comment]
Thank you! Should be enough to repro the condition. I'll post an update soon.

**Comment by kcq** [comment]
The new 1.24 release ( https://github.com/docker-slim/docker-slim/releases/tag/1.24 ) should address this issue. Let me know if it's not the case! Thanks a lot!

**Comment by kcq** [comment]
Closing it for now... Please reopen if you still see the same problem.
