### ISSUE TITLE
Docker-Slim with c++ (Webtoolkit / WT / Witty C++) application (using boost too)?

### ISSUE THREAD

**Issue by ClaudioBsh** [docker-slim/docker-slim#56]
Should it be or better is it possible to use Docker-Slim with a c++ executable binary application?

**Comment by kcq** [comment]
It depends on how you build the image. If you use a vanilla base image like Ubuntu, Debian or even Alpine you should get a (much) smaller image.

**Comment by plinom** [comment]
Yes, right
