### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by WtfJoke** [docker-slim/docker-slim#57]
Are there any plans to make docker-slim available for windows?

**Comment by GTANAdam** [comment]
Would be great to have, painful to have this working on windows through workarounds with docker-machine

**Comment by kcq** [comment]
"Fat" images on Windows is definitely a big headache and I know Microsoft is trying to address the problem too. DockerSlim for Windows is possible, but it will require a new Windows-specific sensor. There'll need to be enough interest for this feature to happen. It'll be great if anybody can do a survey. It'll also help if anybody can find a company willing to discover the production use cases.

**Comment by kcq** [comment]
Moving this to the `wishlist`(https://github.com/docker-slim/docker-slim/blob/master/WISHLIST.md)
