### ISSUE TITLE
Can docker-slim be used without Docker?

### ISSUE THREAD

**Issue by probonopd** [docker-slim/docker-slim#60]
Can docker-slim be used without Docker?

My [use case](https://github.com/probonopd/libhookexecv#minimizing) is that I have an application directory that contains an application and everything it needs to run, plus a lot of additional files that it does _not_ need to run. I would like to slim down the directory so that only the stuff that is needed to run the application is kept.

How can I do this, without Docker?

**Comment by kcq** [comment]
This is a potential future feature when DockerSlim is capable of packaging/dockerizing the application. The main gotcha there is the need to support multiple OSes when it's doing run time analysis and that part is OS specific (it's different on Linux and Mac OS X, for example).

**Comment by probonopd** [comment]
For me it would be fully sufficient if this would work on Linux for Linux application bundles.

**Comment by kcq** [comment]
Moving this to the [`wishlist`](https://github.com/docker-slim/docker-slim/blob/master/WISHLIST.md)
