### ISSUE TITLE
docker-slim build images based on centos failed

### ISSUE THREAD

**Issue by hantmac** [docker-slim/docker-slim#62]
Hi, I have ran into an issue when using `docker-slim build ` a image based on centos.
The env of my machine:
mac os 10.14.2 (18C54)
```
docker-slim:
darwin|Tetra|1.22|936f91d2f1f3fc9b09f94e6ce908135108696675|2018-09-08_02:00:42AM (go1.10)
host:
OsName=other
OsBuild=18C54
Version= Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64
Release=18.2.0
Sysname=darwin
docker:
Name=linuxkit-025000000001
KernelVersion=4.9.125-linuxkit
OperatingSystem=Docker for Mac
OSType=linux
ServerVersion=18.09.0
Architecture=x86_64
ApiVersion=1.39
MinAPIVersion=1.12
BuildTime=2018-11-07T00:55:00.000000000+00:00
GitCommit=4d60db4
```

Use `docker-slim build --http-probe myimage`

Some of the output error:
```
docker-slim: container stdout:
2019-01-11 06:22:15,033 CRIT Supervisor running as root (no user in config file)
2019-01-11 06:22:15,070 INFO supervisord started with pid 19
2019-01-11 06:22:16,087 INFO spawned: 'nginx' with pid 23
2019-01-11 06:22:16,095 INFO spawned: 'jumpserver' with pid 24
......
time="2019-01-11T06:22:13Z" level=info msg="sensor: monitor starting..."
time="2019-01-11T06:22:13Z" level=info msg="fanmon: Run"
time="2019-01-11T06:22:13Z" level=info msg="ptmon: Run"
time="2019-01-11T06:32:19Z" level=info msg="fanmon: processor - stopping..."
time="2019-01-11T06:32:19Z" level=info msg="ptmon: processor - stopping..."
time="2019-01-11T06:32:19Z" level=info msg="ptmon: collector - stopping..."
time="2019-01-11T06:32:19Z" level=info msg="ptmon: collector - stopping..."
panic: runtime error: index out of range

......

```

Looking forward to your reply!

**Comment by kcq** [comment]
@hantmac thank you for reporting the issue! This looks like an interesting bug based on that `index out of range` error. Can you also share a bit more about your image? What version of CentOS are you using? What's inside of our container? What kind of application do you have? What language is it? CentOS is not fully supported yet for all application stack, but I hope your issue can get us closer to the future where it is supported as well as Ubuntu, Debian and Alpine.

**Comment by hantmac** [comment]
Thanks for your reply!
- CentOS version： 7.2
- Insider container：Django project
- language： Python
- application：web application

**Comment by kcq** [comment]
@hantmac The new 1.24 release ( https://github.com/docker-slim/docker-slim/releases/tag/1.24 ) introduced CentOS docker image support. Do you mind giving it a try? 

There's also a couple of (new) CentOS/Python examples:
* https://github.com/docker-slim/examples/tree/master/python_centos7_py27
* https://github.com/docker-slim/examples/tree/master/python_centos7_py27_standard

**Comment by hantmac** [comment]
@kcq  docker-slim work well !!!
- CentOS version： 7.2
- Insider container：Django project
- language： Python
- application：web application

The fat image based on centos is 1.61 Gb, after `docker-slim`, it become 160Mb, amazing!

**Comment by kcq** [comment]
Glad to hear it work! Thank you for making `docker-slim` better!
