### ISSUE TITLE
What is the latest release ruby_ubuntu example was able to run after docker-slim?

### ISSUE THREAD

**Issue by ivanovalex02** [docker-slim/docker-slim#65]
On my Ubuntu 16.04, Docker 18.09

 ./run_slim.command leads to:

> Could not find eventmachine-1.2.7 in any of the sources
> Run `bundle install` to install missing gems.

**Comment by kcq** [comment]
Thank you for raising the issue! The upcoming release will address it. ETA the next few days.

**Comment by kcq** [comment]
With version 1.23 all ruby examples should work.
