### ISSUE TITLE
docker-slim died, with the following msg: level=fatal msg="docker-slim: failure" error="unexpected event type"

### ISSUE THREAD

**Issue by dforouhari** [docker-slim/docker-slim#66]
Running docker-slim failed with a 'fatal' error msg. Plz see below for the details:

Build env: CentOS 7
Docker version: 18.03.0-ce, build 0520e24
Docker-slim version: 1.23
Docker img info:
   Ubuntu: 16.04
   Code in Bash + Python
   Size = 1.6GB

Output of docker-slim:
$ ./docker-slim build --http-probe  img_demo
docker-slim[build]: state=started
docker-slim[build]: info=params target=img_demo continue.mode=enter
docker-slim[build]: state=inspecting.image
docker-slim[build]: info=image id=sha256:bbb4e2cdbb403e8a4508a7921647b1df580ea0a00c0b7f3fa59ae540e39f6129 siz                                             e.bytes=1622646238 size.human=1.6 GB
docker-slim[build]: state=inspecting.container
**time="2019-02-04T13:27:42-08:00" level=fatal msg="docker-slim: failure" error="unexpected event** type" stack="                                             goroutine 1 [running]:
runtime/debug.Stack(0x3, 0xc0000c0b40, 0xc00000ef00)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/docker-slim/docker-slim/pkg/utils/errutils.FailOn(0x8fb8a0, 0xc0000472b0)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/pkg/utils/errutils/er                                             rutils.go:14 +0x51
github.com/docker-slim/docker-slim/internal/app/master/commands.OnBuild(0x0, 0x0, 0x88a600, 0x0, 0x0, 0xc0001                                             3c0f0, 0x7ffdd0899774, 0x8, 0x0, 0x0, ...)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/c                                             ommands/build.go:115 +0xc47
github.com/docker-slim/docker-slim/internal/app/master.init.0.func5(0xc000146140, 0x0, 0xc000146140)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/c                                             li.go:480 +0xd76
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.HandleAction(0x7f26c0, 0x8a0b00, 0xc0001                                             46140, 0xc000140000, 0x0)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/cod                                             egangsta/cli/app.go:485 +0xc8
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.Command.Run(0x884f35, 0x5, 0x0, 0x0, 0xc                                             000047530, 0x1, 0x1, 0x89a23e, 0x3e, 0x0, ...)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/cod                                             egangsta/cli/command.go:207 +0x991
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.(*App).Run(0xc000010ea0, 0xc00000e080, 0                                             x4, 0x4, 0x0, 0x0)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/cod                                             egangsta/cli/app.go:250 +0x6ea
github.com/docker-slim/docker-slim/internal/app/master.runCli()
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/c                                             li.go:730 +0x55
github.com/docker-slim/docker-slim/internal/app/master.Run()
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/a                                             pp.go:6 +0x25
main.main()
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/cmd/docker-slim/main.                                             go:8 +0x20
" version="linux|Tetra|1.23|8488277befdf57a173acc64973f984caab551ed2|2019-02-03_04:05:17PM (go1.11.1)"

**Comment by kcq** [comment]
Thank you for reporting this! I really appreciate! Can you enable debugging and try it again. It's a good idea to enable container logging too. With both enabled your command should look like this: `./docker-slim --debug build --show-clogs --http-probe img_demo`

**Comment by dforouhari** [comment]
Hey Kyle. Here is the partial debug output. Hope it helps.  Pls don't share
this info with public.
Danesh

time="2019-02-11T13:25:54-08:00" level=info msg="starting instrumented
'fat' container..." app=docker-slim command=build
time="2019-02-11T13:25:54-08:00" level=debug msg="RunContainer: default
exposed ports => map[docker.Port]struct {}{"65501/tcp":struct {}{},
"65502/tcp":struct {}{}}"
time="2019-02-11T13:25:54-08:00" level=info msg="RunContainer: created
container =>
9695d5c8f7c21fc3cd70214277b791a65678794a17e8edff140892f63c377de9"
time="2019-02-11T13:25:55-08:00" level=debug msg="RunContainer: container
NetworkSettings.Ports =>
map[docker.Port][]docker.PortBinding{"65501/tcp":[]docker.PortBinding{docker.PortBinding{HostIP:"0.0.0.0",
HostPort:"32771"}},
"65502/tcp":[]docker.PortBinding{docker.PortBinding{HostIP:"0.0.0.0",
HostPort:"32770"}}}"
time="2019-02-11T13:25:55-08:00" level=debug msg="cmdChannelAddr=tcp://
127.0.0.1:32771 evtChannelAddr=tcp://127.0.0.1:32770"
time="2019-02-11T13:25:55-08:00" level=debug msg="sendCmd(&{bash [-c
./img_demo 2 5 10.3.2.63] [] []})"
time="2019-02-11T13:25:55-08:00" level=debug msg="getEvt()"
time="2019-02-11T13:27:55-08:00" level=debug msg="getEvt(): channel.Recv()
- done"
time="2019-02-11T13:27:55-08:00" level=info msg="RunContainer: sensor event
=>"
time="2019-02-11T13:27:55-08:00" level=fatal msg="docker-slim: failure"
error="unexpected event type" stack="goroutine 1 [running]:
runtime/debug.Stack(0xc00019a480, 0xc000148000, 0xc000110e48)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24
+0xa7
github.com/docker-slim/docker-slim/pkg/utils/errutils.FailOn(0x8fb8a0,
0xc0000712a0)
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/pkg/utils/errutils/errutils.go:14 +0x51
github.com/docker-slim/docker-slim/internal/app/master/commands.OnBuild(0x0,
0x0, 0x88a601, 0x0, 0x0, 0xc00015c180, 0x7ffe7937177d, 0xf, 0x0, 0x0, ...)
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/internal/app/master/commands/build.go:115
+0xc47
github.com/docker-slim/docker-slim/internal/app/master.init.0.func5(0xc000174140,
0x100, 0xc000174140)
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/internal/app/master/cli.go:480 +0xd76
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.HandleAction(0x7f26c0,
0x8a0b00, 0xc000174140, 0xc000160000, 0x0)
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/app.go:485
+0xc8
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.Command.Run(0x884f35,
0x5, 0x0, 0x0, 0xc000071520, 0x1, 0x1, 0x89a23e, 0x3e, 0x0, ...)
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/command.go:207
+0x991
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.(*App).Run(0xc00009ab60,
0xc00007e120, 0x6, 0x6, 0x0, 0x0)
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/app.go:250
+0x6ea
github.com/docker-slim/docker-slim/internal/app/master.runCli()
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/internal/app/master/cli.go:730 +0x55
github.com/docker-slim/docker-slim/internal/app/master.Run()
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/internal/app/master/app.go:6 +0x25
main.main()
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/cmd/docker-slim/main.go:8 +0x20

 -.. ..-.

**Comment by dforouhari** [comment]
Hey Kyle,
Any update on this?
Thx
 -.. ..-.

**Comment by kcq** [comment]
This appears to be IPC related. The master app most likely timed out waiting for the start event. It's not clear why without seeing the container logs too. Can you see if you have any container logs for the container with the name that starts with `dockerslimk_`. Can you check if it's still running or if it exited with an error code?

**Comment by dforouhari** [comment]
Hey Kyle,
The app exited with exit code 1.
Here is the log for the container (when it was running)
[dforouhari@dev05 ~]$ docker logs 9695d5c8f7c2
time="2019-02-11T21:25:55Z" level=debug msg="sensor: sysinfo =>
system.SystemInfo{Sysname:"Linux", Nodename:"9695d5c8f7c2",
Release:"3.10.0-693.el7.x86_64", Version:"#1 SMP Tue Aug 22 21:09:27 UTC
2017", Machine:"x86_64", Domainname:"(none)", OsName:"Ubuntu 16.04.5 LTS
(Xenial Xerus)", OsBuild:""}"
time="2019-02-11T21:25:55Z" level=debug msg="sensor: kernel flags =>
map[string]string(nil)"
time="2019-02-11T21:25:55Z" level=info msg="sensor: args =>
[]string{"/opt/dockerslim/bin/sensor", "-d"}"
time="2019-02-11T21:25:55Z" level=debug msg="sensor: cwd => "/img_demo""
time="2019-02-11T21:25:55Z" level=debug msg="sensor: setting up channels..."
time="2019-02-11T21:25:55Z" level=info msg="sensor: creating event
publisher..."
time="2019-02-11T21:25:55Z" level=info msg="sensor: creating cmd server..."
time="2019-02-11T21:25:55Z" level=info msg="sensor: waiting for commands..."
time="2019-02-11T21:25:55Z" level=debug msg="sensor: cmd server - waiting
for a command..."
time="2019-02-11T21:25:55Z" level=debug msg="sensor: cmd server - got a
command =>
{"name":"cmd.monitor.start","data":{"app_name":"bash","app_args":["-c","./img_demo
2 5 10.3.2.63"]}}"
time="2019-02-11T21:25:55Z" level=debug msg="sensor: cmd server - waiting
for a command..."
time="2019-02-11T21:25:55Z" level=debug msg="
sensor: command => &{bash [-c ./img_demo 2 5 10.3.2.63] [] []}"
time="2019-02-11T21:25:55Z" level=debug msg="sensor: 'start' monitor
command (&command.StartMonitor{AppName:"bash", AppArgs:[]string{"-c",
"./img_demo 2 5 10.3.2.63"}, Excludes:[]string(nil),
Includes:[]string(nil)})"
time="2019-02-11T21:25:55Z" level=info msg="sensor: monitor starting..."
time="2019-02-11T21:25:55Z" level=info msg="fanmon: Run"
time="2019-02-11T21:25:55Z" level=fatal msg="docker-slim: failure"
error="operation not permitted" stack="goroutine 1 [running]:
runtime/debug.Stack(0xffffffffffffffff, 0x5e4ae0, 0xc000014868)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24
+0xa7
github.com/docker-slim/docker-slim/pkg/utils/errutils.FailOn(0x5e4ae0,
0xc000014868)
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/pkg/utils/errutils/errutils.go:14 +0x51
github.com/docker-slim/docker-slim/internal/app/sensor/monitors/fanotify.Run(0x5b866a,
0x1, 0xc00006a540, 0x12)
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/internal/app/sensor/monitors/fanotify/monitor.go:38
+0x8f
github.com/docker-slim/docker-slim/internal/app/sensor.monitor(0xc00004a070,
0xc00004a0e0, 0xc00006a420, 0xc00004c540, 0xc00004a150, 0xc0000e4060,
0xc000014680, 0x9)
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/internal/app/sensor/app.go:48 +0x123
github.com/docker-slim/docker-slim/internal/app/sensor.Run()
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/internal/app/sensor/app.go:135 +0x66f
main.main()
        /Users/q/docker-slim/docker-slim/_gopath/src/
github.com/docker-slim/docker-slim/cmd/docker-slim-sensor/main.go:8 +0x20
" version="linux|Tetra|latest|latest|latest (go1.11.1)"

HTH
 -.. ..-.

**Comment by kcq** [comment]
Thank you! That's exactly what I was looking for :)

The master timed out waiting for the sensor because the sensor exited when it encountered the 'operation not permitted' error from our container log trace. It's strange that it happened with Ubuntu 16.04. There's enough info for a repro. I'll post an update soon.

Thanks again for helping me track this down! I really appreciate it.

**Comment by kcq** [comment]
One more question... How is your Dockerfile structured? What user do you use in the image? Can you share the user related Dockerfile lines?

**Comment by dforouhari** [comment]
Hey Kyle,
glad to be of help.
Look fwd to using the fixed version.
Danesh
 -.. ..-.

**Comment by dforouhari** [comment]
I'll send the info on Monday.
HTH
 -.. ..-.

**Comment by dforouhari** [comment]
Here is some info that u requested (regarding Dockerfile, USER, ..)
In the Dockerfile:
...
ARG uid=foo
...
RUN sudo useradd ... ${uid}
...
USER ${uid}
...

HTH
Danesh


 -.. ..-.

**Comment by kcq** [comment]
Thanks for confirming that you are using a custom user in your image. This is the reason for failure because that user isn't privileged enough to start fsnotify. Working on an enhancement to support images with non-default users. Thanks for your help identifying the problem!

**Comment by dforouhari** [comment]
Glad to be of help.
Look fwd to using the fix.

Danesh
 -.. ..-.

**Comment by dforouhari** [comment]
Hey Kyle,
I might not have much more time left to use/play with my Docker code,
beyond next Thr (March 7th).
Any idea when u might have a patch/fix to try?
Thanks
Danesh
 -.. ..-.

**Comment by kcq** [comment]
The new 1.24 release ( https://github.com/docker-slim/docker-slim/releases/tag/1.24 ) should address this problem.

**Comment by dforouhari** [comment]
Hi Kyle.
Thanks for the update...I'll give it a try when I  have some free time
(probably next wk).

Best,
Danesh
 -.. ..-.

**Comment by dforouhari** [comment]
Hi Kyle.
There is  a new problem with the 1.24 version...it seems to be 'permission'
related.
Here is the info:
1. I am logged with my uid (dforouhari)
2. docker-slim failed with/at
docker-slim[build]: state=building message='building minified image'
time="2019-03-19T16:45:56-07:00" level=fatal msg="docker-slim: failure"
error=*"no permission to read from* '/home/dforouhari/3rd
_party_src/dist_linux/.images/752f8eea14330275ff2c3e1611f7db98cc13cfa9c9cc635b6970a7afb0f113e3/artifacts/files/root/.ssh/id_rsa
              '" stack="goroutine 1 [running]:
3.
[dforouhari@artifacts]$ pwd
/home/dforouhari/3rd_party_src/dist_linux/.images/752f8eea14330275ff2c3e1611f7db98cc13cfa9c9cc635b6970a7afb0f113e3/artifacts
[dforouhari@artifacts]$ ls -lt
total 96
-rw-r--r--  1 dforouhari dforouhari   176 Mar 19 16:45 Dockerfile
-rw-r--r--  1 dforouhari dforouhari  3700 Mar 19 16:45 img_demo-seccomp.json
-rw-r--r--  1 dforouhari dforouhari  3089 Mar 19 16:45
img_demo-apparmor-profile
-rw-r--r--  1 root       root       81795 Mar 19 16:45 creport.json   #Question
is the uid/gid root what u expect?
drwxr-xr-x 10 root       root         101 Mar 19 16:45 files
#Question is the uid/gid root what u expect?
-rw-r--r--  1 dforouhari dforouhari  2691 Mar 19 16:44 Dockerfile.fat

Here is the perm on the specific file that docker-slim complained about
[dforouhari@artifacts]$ ls -l
/home/dforouhari/3rd_party_src/dist_linux/.images/752f8eea14330275ff2c3e1611f7db98cc13cfa9c9cc635b6970a7afb0f113e3/artifacts/files/root/.ssh/id_rsa
*-rw------- 1 root root* 1675 Mar 19 16:44


HTH
Danesh
 -.. ..-.

**Comment by kcq** [comment]
@dforouhari This is interesting and definitely different :-) `docker-slim` copied the artifacts from the target image including the file permissions and one of those files isn't accessible by a regular user on your host machine. Need to think about how to solve this... One possible solution is for you to run `docker-slim` from a root shell.

**Comment by kcq** [comment]
@dforouhari i'll create a separate issue for the permission problem

**Comment by dforouhari** [comment]
Look fwd to the fix.
 -.. ..-.

**Comment by kcq** [comment]
Here's the new issue to track it: https://github.com/docker-slim/docker-slim/issues/73
