### ISSUE TITLE
How do I get deleted file list and file sizes from docker slim

### ISSUE THREAD

**Issue by aparnaedu** [docker-slim/docker-slim#67]
How do I get delete files and file sizes from docker slim.

**Comment by kcq** [comment]
Are you looking for a convenient way to list the files not included in the minified image?

This might be a nice feature. For now you can accomplish this by doing a diff between the files in the original and the minified container images.

**Comment by aparnaedu** [comment]
Hi - How can I run the eclipse source code and figure out to list the files removed from the minified image. 
So I can create a new docker-slim version to run which can give the list.

**Comment by kcq** [comment]
Moving this to the [`wishlist`](https://github.com/docker-slim/docker-slim/blob/master/WISHLIST.md)
