### ISSUE TITLE
Docker-slim and gitlab runner with Hugo image

### ISSUE THREAD

**Issue by dmpe** [docker-slim/docker-slim#68]
Hi Kyle, 
Great project !! Thank you very much for it. 

I would have 1 use case which I would like to know if docker-slim can be used for. 

We use GitLab and recently started to play with GitLab Pages and <http://gohugo.io>. 
My workflow without docker slim is as of now following:

- Create Docker Image with hugo (~1.5GB), based on `golang:1.11-stretch` which contains CMD to bash. 
- In GitLab, we have a hugo project and whenever you commit, GitLab Runner fetches latest Docker Image from above step and executes `hugo` command which creates HTML website.

My question would be if we can modify our workflow to have following (i.e. can dockerslim be used for it):

- Create Docker Image with hugo (~1.5GB), based on `golang:1.11-stretch` which fetches and executes simple/base Hugo project. The resulting slim image would be like now < 200 MB and it would contain CMD to bash, again.
- In GitLab, we have an up-to-date hugo project and as previously, whenever you commit, GitLab Runner now fetches latest Docker `Slim Image` and executes `hugo` command which must be already present in the slim image - given that we create a docker slim image with base hugo project.

Would do you think?
Thank you

**Comment by HazCod** [comment]
Hugo is Go, meaning it's a static binary.
You could just use a `scratch` image with hugo in it. No need to use a full debian.

**Comment by dmpe** [comment]
OK, got it. 
Thanks

**Comment by kcq** [comment]
For a compiled app with no or very few easy to manage dependencies it's pretty straight forward to create your own small image with `scratch` especially when somebody already created a Dockerfile for it. Good to have options :-)
