### ISSUE TITLE
How about add a command 'docker-slim update' to auto-update?

### ISSUE THREAD

**Issue by hantmac** [docker-slim/docker-slim#71]
When I update docker-slim, I feel it not graceful. How about add a command `docker-slim update` to update it ?

**Comment by kcq** [comment]
Thanks for the suggestion! The next version will have automatic version checks. A command to download and install a new/different version will be a useful feature too.

**Comment by kcq** [comment]
@hantmac The `update` command is now a part of the latest release (1.25.0). Now you can run `docker-slim update` just like you asked for :-)

**Comment by hantmac** [comment]
**Great! 👍👍**
