### ISSUE TITLE
minified ros:indigo-perception does not work

### ISSUE THREAD

**Issue by KikiCS** [docker-slim/docker-slim#76]
Hi, I was testing this beautiful tool, I successfully minified an alpine image, so I tried ros:indigo-perception. docker run ros.slim is not working so I hope posting here can be of help.
**System information**
Linux ctest 4.4.0-145-generic #171-Ubuntu SMP Tue Mar 26 12:43:40 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
go version go1.12.4 linux/amd64
Docker version 18.09.6, build 481bc77

``` 
$ sudo ./docker-slim build ros:indigo-perception
docker-slim[build]: state=started
docker-slim[build]: info=params target=ros:indigo-perception continue.mode=enter
docker-slim[build]: state=inspecting.image
docker-slim[build]: info=image id=sha256:d52041d5ee34db1fe14db00d12cd8c13030d755eb4c8c9883a7c60d607c3bf0c size.bytes=1812321964 size.human=1.8 GB
docker-slim[build]: info=image.layers index=0 name='ros' tags='indigo-perception'
docker-slim[build]: state=inspecting.container
docker-slim[build]: info=container status=created id=f93ae024f11bea100460c969558bd4b7e349cc7d256bddbe320c9a557c55bddd
docker-slim[build]: info=cmd.startmonitor status=sent
docker-slim[build]: info=event.startmonitor.done status=received
docker-slim[build]: info=container name=dockerslimk_2368_20190508100303 id=f93ae024f11bea100460c969558bd4b7e349cc7d256bddbe320c9a557c55bddd target.port.list=[] target.port.info=[]
docker-slim[build]: info=prompt message='press <enter> when you are done using the container'

docker-slim[build]: state=processing
docker-slim[build]: state=building message='building minified image'
docker-slim[build]: state=completed
docker-slim[build]: info=results status='MINIFIED BY 150.19X [1812321964 (1.8 GB) => 12066905 (12 MB)]'
docker-slim[build]: info=results  image.name=ros.slim image.size='12 MB' data=true
docker-slim[build]: info=results  artifacts.location='/home/ubuntu/dist_linux/.docker-slim-state/images/d52041d5ee34db1fe14db00d12cd8c13030d755eb4c8c9883a7c60d607c3bf0c/artifacts'
docker-slim[build]: info=results  artifacts.report=creport.json
docker-slim[build]: info=results  artifacts.dockerfile.original=Dockerfile.fat
docker-slim[build]: info=results  artifacts.dockerfile.new=Dockerfile
docker-slim[build]: info=results  artifacts.seccomp=ros-seccomp.json
docker-slim[build]: info=results  artifacts.apparmor=ros-apparmor-profile
docker-slim[build]: state=done
```
Error:
```
$ sudo docker run ros.slim sleep 70
mktemp: failed to create file via template ‘/tmp/setup.sh.XXXXXXXXXX’: No such file or directory
```
Thanks!

**Comment by KikiCS** [comment]
I read in a past issue with CentOS that I should try a whole application on top of a docker image so will try asap.

> Base OS images are not good candidates for minification. It's designed to minify around your custom application and what that application needs, so a better approach would be to build your application docker image on top of the base CentOS image and then minify that.
#55

**Comment by kcq** [comment]
Very interesting... I'd love to know more about this distro and what kind of applications you can build with it and how they work... Yes, you really need an application or service built on top of your base image because without an application it's hard to know what you need and what you don't. You can hack around by using the `--include-path`, `--include-exe`, `--include-bin` and `include-shell` flags to choose which binaries, components, files and directories you want, but they are meant as extra helpers, so it'll be more work to accomplish the same if you had an actual application because now you need to explicit decide what goes and what stays in your container :)

**Comment by KikiCS** [comment]
Thanks for your help! The whole idea with ROS is plug&play with robots...
I close this issue for now and will get back with updates when the project I am working on progresses.

**Comment by kcq** [comment]
@KikiCS Feel free to ping me anytime if you have any questions! I'm also curious to learn more about your use cases for `docker-slim`, why you'd be interested in it and what you wish you could do and what kind of environments/system you are targeting to deploy your app and the constraints you have to deal with.
