### ISSUE TITLE
Any plan to support windows?

### ISSUE THREAD

**Issue by mrtylerzhou** [docker-slim/docker-slim#77]
as the title said

**Comment by kcq** [comment]
Native Windows support is possible, but it's quite a bit of extra effort. It all depends on how many people want/need this capability :-) In the near future the best bet will be the newly announced WSL 2 in Windows.

**Comment by mrtylerzhou** [comment]
awesome.Through i deploy my applications on linux,but in deployment,I like to try everything on windows

**Comment by kcq** [comment]
With WSL 2 it looks like we'll get parity with the Mac OS X local experience :)

**Comment by kcq** [comment]
@mrtylerzhou I'd love to learn more about your use cases, the application stacks you are using (and how) and what you wish the tool can do for you. Would you be open to quick chat on Google Hangout, Skype, WhatsApp, Telegram or whatever you prefer?

**Comment by mrtylerzhou** [comment]
primarily,I build my dotnet core images on docker on windows.After testing out,I'll use a linux machine to build the production level image.The reason why I use windows machine to build testing images is that I feel comfortable working on windows.What i wish is that all great tools have a windows version.

**Comment by kcq** [comment]
@mrtylerzhou How much do you know about .NET Core on Linux? Can use some help to make sure it's well supported with `docker-slim` ;-)

**Comment by mrtylerzhou** [comment]
I'm working in sto express in China.Currently,we are planning to migrate our  traditional applications to .net core and host them on alibaba cloud service.Currently I'm investigating how to optimize docker images.Docker slim is interesting,And I'll have a try it in testing environment and give you feedbacks.

**Comment by kcq** [comment]
@mrtylerzhou if it's not a secret... why do you care about optimizing docker images? also curious... how did you find out about `docker-slim`?

**Comment by mrtylerzhou** [comment]
I just take optimizing into consideration.In fact,up to now,microsoft base image is about 300M,it is acceptable.But the smaller,the better.I found docker slim by keyword **docker slim**,there really have one;-)

**Comment by mrtylerzhou** [comment]
alibaba have a instruction that the image's kernal version should match host's kernal version.we may also make a custom base image instead of using microsoft's

**Comment by kcq** [comment]
@mrtylerzhou , thanks for the context! I'm curious... Is image size your main and only container related concern or do you have other container pain points you wish you could address? Do you do anything with your containers to make them more secure? Is there anything you wish you could do with your containers at run time (related to monitoring or visibility)?

**Comment by kcq** [comment]
moving this to WISHLIST.md
