### ISSUE TITLE
how to push the slimmed images

### ISSUE THREAD

**Issue by ThomasSchoenbeck** [docker-slim/docker-slim#84]
Hi there,

sorry for the question, but the documentation does not describe this part. How do we push our slimmed images in a container registry?

**Comment by kcq** [comment]
@ThomasSchoenbeck You don't need to do anything special... The minified images are just like any other Docker images (`docker push your_minified_image_name`). If the name of the original image didn't include your DockerHub username or if you used a custom tag with `docker-slim` then you'll need to first tag the minified image, so the tag includes your DockerHub username (`docker tag your_dockerhub_username/your_minified_image_name`). You'll need to be logged in to DockerHub first, of course (`docker login ....`).

**Comment by kcq** [comment]
@ThomasSchoenbeck I'm curious if you are looking for an option to automatically push the minified image to DockerHub when `docker-slim` is done...

**Comment by ThomasSchoenbeck** [comment]
Hi there. My idea was to include ```docker-slim``` into a CI/CD pipeline, to always have it run at the end to optimize the output docker image. I didn't realize that it the tool needs docker to work. But i guess that's the case.

Of course inside the CI/CD pipeline, after optimizing the image, i want to push back the image into the registry. So i would add this as command into the pipeline. In my case the destination will not be DockerHub, but our companies OpenShift Image Registry or a GitLab Repo Registry.

I guess i will try docker-slim in combination with podman. See if they work well together.
