### ISSUE TITLE
Http probe request body

### ISSUE THREAD

**Issue by jishminor** [docker-slim/docker-slim#86]
Based on my inspection so far, it appears that request bodies are not handled in [custom_probe.go](https://github.com/docker-slim/docker-slim/blob/master/internal/app/master/inspectors/container/probes/http/custom_probe.go)? 

I am using the following json for my probe commands:
```
{
    "commands":
    [
     {
       "protocol": "http",
       "method": "POST",
       "resource": "/resource",
       "headers": ["Content-Type:application/json"],
       "body": "key=value, key2=value"
     }
    ]
}
```

And the following invocation of docker slim build v1.25.2:
```
./docker-slim build --continue-after signal --http-probe-cmd-file tests/probeCmds.json --include-shell --tag $CONTAINER_TEST_IMAGE_SLIM $CONTAINER_TEST_IMAGE
```

Upon running the probe I noticed there was no body in the request being received. 

Further, I noticed the following output in the logs:
```
docker-slim[build]: state=http.probe.running
docker-slim[build]: info=http.probe.call status=400 method=POST target=http://docker:32770/resource attempt=1  time=2019-07-23T19:42:14Z
docker-slim[build]: info=http.probe.call status=404 method=GET target=http://docker:32770/ attempt=1  time=2019-07-23T19:42:14Z
docker-slim[build]: info=http.probe.summary total=2 failures=0 successful=2
```
showing that both a GET and a POST request were attempted although I am specifying only the POST request in my json.

**Comment by kcq** [comment]
@jishminor interesting... let me investigate... Thank you for finding this!

**Comment by kcq** [comment]
Turns out the unexpected GET is the default/extra call the probe adds on its own (GET /): https://github.com/docker-slim/docker-slim/blob/0d32afea9a3c3df78fbe0505c6b547d1a1fdbe34/internal/app/master/cli.go#L593

**Comment by kcq** [comment]
@jishminor the new 1.25.3 release ( https://dockersl.im/downloads.html or you can just run `docker-slim update`) should have the fix for this custom HTTP POST probe bodies. Let me know if it works for you or not.

**Comment by jishminor** [comment]
Issue is fixed. Had to change probe command body to the following:
```
{
    "commands":
    [
     {
       "protocol": "http",
       "method": "POST",
       "resource": "/resource",
       "headers": ["Content-Type:application/json"],
       "body": "{\"key\":\"value\", \"key2\":\"value\"}"
     }
    ]
}
```
As I didn't realize the body is just interpreted as a string. I assumed that the json would be formed using the key value pairs specified in the body. Improved documentation around this would be beneficial.
