### ISSUE TITLE
"permission denied" failure" error="Get http://unix.sock/images/d9dc67eb0ba7/json using podman image

### ISSUE THREAD

**Issue by rubyfin** [docker-slim/docker-slim#91]
Getting the following error:

```
[me@myhost]$ docker-slim build --http-probe d9dc67eb0ba7
docker-slim[build]: info=http.probe message='using default probe'
docker-slim[build]: state=started
docker-slim[build]: info=params target=d9dc67eb0ba7 continue.mode=enter
docker-slim[build]: state=image.inspection.start
time="2019-10-09T17:20:37-04:00" level=fatal msg="docker-slim: failure" error="Get http://unix.sock/images/d9dc67eb0ba7/json: dial unix /var/run/docker.sock: connect: permission denied" stack="goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x31)
        /usr/local/Cellar/go/1.11.1/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/docker-slim/docker-slim/pkg/util/errutil.FailOn(0x98b4a0, 0xc0001806c0)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/pkg/util/errutil/errutil.go:14 +0x51
github.com/docker-slim/docker-slim/internal/app/master/commands.OnBuild(0x86d701, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0001800f0, 0x0, 0x0, 0x7ffca8513905, ...)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/commands/build.go:154 +0x887
github.com/docker-slim/docker-slim/internal/app/master.init.0.func6(0xc000188140, 0x0, 0xc000188140)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/cli.go:682 +0x1310
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.HandleAction(0x85c9c0, 0x920a38, 0xc000188140, 0xc000036100, 0x0)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/app.go:485 +0xc8
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.Command.Run(0x900af0, 0x5, 0x0, 0x0, 0xc0000997d0, 0x1, 0x1, 0x919408, 0x3e, 0x0, ...)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/command.go:207 +0x991
github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli.(*App).Run(0xc0000c8b60, 0xc0000ae000, 0x4, 0x4, 0x0, 0x0)
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/vendor/github.com/codegangsta/cli/app.go:250 +0x6ea
github.com/docker-slim/docker-slim/internal/app/master.runCli()
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/cli.go:1027 +0x55
github.com/docker-slim/docker-slim/internal/app/master.Run()
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/internal/app/master/app.go:6 +0x25
main.main()
        /Users/q/docker-slim/docker-slim/_gopath/src/github.com/docker-slim/docker-slim/cmd/docker-slim/main.go:8 +0x20
" version="linux|Transformer|1.25.3|b5aef546a575de242b2c3ace97e1fc11f028b137|2019-08-04_04:31:18PM"
```

I actually do not use docker - I use podman. Do I need to configure docker-slim to work with podman? Some debug info:

`
[me@myhost]$ docker-slim --debug version
time="2019-10-09T17:22:35-04:00" level=debug msg="sysinfo => system.SystemInfo{Sysname:"Linux", Nodename:"myhost", Release:"3.10.0-862.el7.x86_64", Version:"#1 SMP Wed Mar 21 18:14:51 EDT 2018", Machine:"x86_64", Domainname:"(none)", OsName:"Red Hat Enterprise Linux Server 7.7 (Maipo)", OsBuild:""}"
time="2019-10-09T17:22:35-04:00" level=debug msg="docker-slim: new Docker client (default) [6]"
time="2019-10-09T17:22:35-04:00" level=debug msg="docker-slim: configured DOCKER_HOST env var"
docker-slim[version]: linux|Transformer|1.25.3|b5aef546a575de242b2c3ace97e1fc11f028b137|2019-08-04_04:31:18PM
time="2019-10-09T17:22:36-04:00" level=debug msg="version.Check: http status = 200 OK" app=docker-slim
Version Status: your have the latest version
host:
OsName=Red Hat Enterprise Linux Server 7.7 (Maipo)
OsBuild=
Version=#1 SMP Wed Mar 21 18:14:51 EDT 2018
Release=3.10.0-862.el7.x86_64
Sysname=Linux
docker:
error getting docker info
`

**Comment by kcq** [comment]
@rubyfin This will be an interesting feature to explore. Right now `docker-slim` expects to have `Docker` installed on the same machine and it uses the `Docker` API to run containers and to create new images. The same will need to be done with Podman.

**Comment by rubyfin** [comment]
> @rubyfin This will be an interesting feature to explore. Right now `docker-slim` expects to have `Docker` installed on the same machine and it uses the `Docker` API to run containers and to create new images. The same will need to be done with Podman.

Gotcha, I thought so too. I think it will be a great feature to explore, as podman is a drop-in replacement for docker, and I think will be only gaining in popularity, especially in corporate environments. 

I will be more than happy to help test out any new features on podman. :)

**Comment by kcq** [comment]
moving this to WISHLIST.md
