### ISSUE TITLE
Binaries not downloadable at present

### ISSUE THREAD

**Issue by iamwithnail** [docker-slim/docker-slim#93]
The links from the main README page aren't working at present - getting what looks like an S3 error: 

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>60EDA56F7C740187</RequestId>
<HostId>
QEuSnlM5QTr09/aCnTMDJRazSesKbiNGELV9Ky8Gw876k7wZj0NZxnUq+Zpru8cHoWe9lFudgcc=
</HostId>
</Error>`
```

I was downloading the linux one, but it's the same across all three.

**Comment by kcq** [comment]
Thanks for reporting @iamwithnail! Sorry for that! Investigating...

**Comment by kcq** [comment]
Should be good now

**Comment by iamwithnail** [comment]
That's great, thanks!  All working now.
