### ISSUE TITLE
cannot unmarshal array into Go value of type docker.Image

### ISSUE THREAD

**Issue by vattezhang** [docker-slim/docker-slim#95]
I have a problem when using the docker-slim, is there something wrong with my method or environment ?

[root@sss docker_slim_test]# ./dist_linux/docker-slim build .
docker-slim[build]: info=http.probe message='using default probe'
docker-slim[build]: state=started
docker-slim[build]: info=params target=. continue.mode=probe
docker-slim[build]: state=image.inspection.start
time="2019-12-01T16:50:53+08:00" level=fatal msg="docker-slim: failure" error="json: cannot unmarshal array into Go value of type docker.Image" stack="goroutine 1 [running]:\nruntime/debug.Stack(0x0, 0x0, 0xc000189e01)\n\truntime/debug/stack.go:24 +0x9d\ngithub.com/docker-slim/docker-slim/pkg/util/errutil.FailOn(0xb6be20, 0xc0000c5720)\n\tgithub.com/docker-slim/docker-slim@/pkg/util/errutil/errutil.go:14 +0x54\ngithub.com/docker-slim/docker-slim/internal/app/master/commands.OnBuild(0x9c4e01, 0xa92aae, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa80000, 0xc000163440, ...)\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/commands/build.go:178 +0x91d\ngithub.com/docker-slim/docker-slim/internal/app/master.init.0.func6(0xc0000d8b00, 0x0, 0xc0000dedb0)\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/cli.go:775 +0x1709\ngithub.com/urfave/cli.HandleAction(0x9b03a0, 0xab7478, 0xc0000d8b00, 0xc0000d8b00, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:523 +0xbe\ngithub.com/urfave/cli.Command.Run(0xa8978f, 0x5, 0x0, 0x0, 0xc00018c520, 0x1, 0x1, 0xaab688, 0x3e, 0x0, ...)\n\tgithub.com/urfave/cli@v1.22.1/command.go:174 +0x51c\ngithub.com/urfave/cli.(*App).Run(0xc00019c000, 0xc000094150, 0x3, 0x3, 0x0, 0x0)\n\tgithub.com/urfave/cli@v1.22.1/app.go:276 +0x718\ngithub.com/docker-slim/docker-slim/internal/app/master.runCli()\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/cli.go:1159 +0x55\ngithub.com/docker-slim/docker-slim/internal/app/master.Run()\n\tgithub.com/docker-slim/docker-slim@/internal/app/master/app.go:6 +0x25\nmain.main()\n\tgithub.com/docker-slim/docker-slim@/cmd/docker-slim/main.go:8 +0x20\n" version="linux|Transformer|1.26.1|xxxxxxxxxxxxxxxxxxxxxxxxxx|2019-11-28_04:37:59PM"

**Comment by kcq** [comment]
@vattezhang Thank you for opening the ticket! Can you share a bit more about your setup and what you were trying to do when you executed `docker-slim` like this: `./dist_linux/docker-slim build .`. Did you want `docker-slim` to build a new Docker image from a Dockerfile you have in your current directory? Trying to understand what that `.` is for :-)

**Comment by vattezhang** [comment]
My pleasure :-)

My setup && What I'm trying to do:
    I just download the latest version of docker-slim, and have download a ubuntu image into my linux system.
    And create a simple dockerfile to build my own docker image.
    The dockerfile is very simple:

        FROM ubuntu:16.04
        RUN touch /tmp/testfile

    When I use "docker build .", it's ok to generate a new docker image.
    Then I want to reduce the size of my image, so I tried to use "docker-slim build ." command.
    Here comes the problem I have presented as above.

**Comment by txxg** [comment]
Any progress?  Same issue happened.

**Comment by jyn514** [comment]
Same issue here, I also tried using the absolute path to the current directory. Does docker-slim require you to used a published docker image? That makes it a little hard to use for development ...

**Comment by jyn514** [comment]
Ah it looks like you have to use an existing image, not a `Dockerfile`. I tried it like this and it worked:

```
docker build --tag some_tag .
docker-slim build some_tag
```

**Comment by kcq** [comment]
@jyn514 @txxg @vattezhang there's a way to use `docker-slim` without an existing Docker image if you prefer to skip the Docker build command (`docker build --tag some_tag .`). `docker-slim` has a build flag for it (`--from-dockerfile`). Here's an example: `docker-slim build --from-dockerfile Dockerfile .` or `docker-slim build --from-dockerfile Dockerfile --tag my_custom_tag_for_slim_image .`

Also note that minifying the test image (with `touch /tmp/testfile` in it and nothing else) won't produce a useful image because it doesn't include any application logic :-)

**Comment by vattezhang** [comment]
@kcq @jyn514 ,thank you for your solution, it works.
"touch /tmp/testfile" is just a test Dockerfile, not a real one :-)
