### ISSUE TITLE
Unable to run docker-slim with non-default args

### ISSUE THREAD

**Issue by hazcod** [docker-slim/docker-slim#96]
dockerslim seems to ignore the initial entrypoint/cmd I set in my original image, making it look for a default user because of unloaded config.

Image: https://github.com/ironPeakServices/iron-nginx

Usage:
```
docker-slim build iron-nginx:1.17.5 -continue-after=enter --new-cmd="-c /nginx.conf"
```

Container logs:
```
time="2019-12-09T08:50:00Z" level=info msg="sensor: args => []string{\"/opt/dockerslim/bin/docker-slim-sensor\"}"
time="2019-12-09T08:50:00Z" level=info msg="sensor: waiting for commands..."
time="2019-12-09T08:50:00Z" level=info msg="sensor: monitor starting..."
time="2019-12-09T08:50:00Z" level=info msg="fanmon: Run"
time="2019-12-09T08:50:00Z" level=info msg="ptmon: Run"
2019/12/09 08:50:00 [emerg] 15#15: getpwnam("nginx") failed
nginx: [emerg] getpwnam("nginx") failed
time="2019-12-09T08:50:00Z" level=info msg="ptmon: collector - exiting... status= 256"
time="2019-12-09T08:50:00Z" level=info msg="ptmon: processor - collector finished =>0"
time="2019-12-09T08:50:03Z" level=info msg="sensor: waiting for monitor to complete startup..."
time="2019-12-09T08:50:03Z" level=info msg="sensor: monitor started (true)..."
```

**Comment by kcq** [comment]
What if you use the "--cmd" parameter?

**Comment by hazcod** [comment]
@kcq Seems to work when I issue `docker-slim build iron-nginx:1.17.5 -continue-after=enter --cmd="-g 'user nonroot;'"`
What user does docker-slim try to use by default?

**Comment by kcq** [comment]
It should also work if you add an explicit 'user' config option to your nginx.conf file. `docker-slim` doesn't run the target app/process as the Dockerfile user when it's inspecting the temporary container it creates. Let me see if I can add an enhancement for this, so this explicit user config option in nginx is not necessary.

**Comment by kcq** [comment]
@hazcod The latest release (1.27.0) adds a number of enhancements that address your non-default container user use cases. Nginx gets executed with the expected `nonroot` user, so it picks up the correct configs without having to add the explicit `user` config in nginx.

**Comment by hazcod** [comment]
Thanks @kcq!
