### ISSUE TITLE
Docs / error confusing: running build in docker fails with `docker.connect.error message='make sure to pass the Docker connect parameters to the docker-slim container'`

### ISSUE THREAD

**Issue by artdgn** [docker-slim/docker-slim#97]
### Sorry but couldn't figure out what to do with this error:
- I'm running docker-slim in docker: `docker run dslim/docker-slim build my-image`
- Got the following output:
```
docker-slim[build]: info=http.probe message='using default probe'
docker-slim[build]: info=docker.connect.error message='make sure to pass the Docker connect parameters to the docker-slim container'
docker-slim[build]: state=exited version=linux|Transformer|1.26.1|2ec04e169b12a87c5286aa09ef44eac1cea2c7a1|2019-11-28_04:54:59PM
```

### Things I've tried:
- Reading / searching the docs. Found the section on "Docker connect" to be confusing, not sure even if related to what I'm trying to do.
- Tried running  `docker run --net=host dslim/docker-slim build my-image`. Same result.
- Tried searching in issues.

**Comment by kcq** [comment]
Sorry for the confusing docs @artdgn . The docs definitely need to be improved...

If you want to use the `docker-slim` Docker image you need to either mount the local docker socket or you need to set the Docker host environment variable when you run the `docker-slim` container.

Here's an example: `docker run -it -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim build my-image`

**Comment by artdgn** [comment]
Thanks for the quick response. I've tried your suggestion, and the error disappeared but it doesn't produce a container:
I run `docker run -it -v /var/run/docker.sock:/var/run/docker.sock dslim/docker-slim build my-repo/my-image`.
I get the following output:

```
docker-slim[build]: info=http.probe message='using default probe'
docker-slim[build]: state=started
docker-slim[build]: info=params target=my-repo/my-image continue.mode=probe
docker-slim[build]: state=image.inspection.start
docker-slim[build]: info=image id=sha256:be7aed72c458772fc1d792d570e7e1a0c594d7d1350b91b4eab392039b99329f size.bytes=1265763671 size.human=1.3 GB
docker-slim[build]: info=image.stack index=0 name='python:3.6' id='sha256:a08c6226131aeb7682d83f350e0ff5cf2b99c6418f00de58e4d6ad3d5c1c1492'
docker-slim[build]: info=image.stack index=1 name='my-repo/my-image:latest' id='sha256:be7aed72c458772fc1d792d570e7e1a0c594d7d1350b91b4eab392039b99329f'
docker-slim[build]: state=image.inspection.done
docker-slim[build]: state=container.inspection.start
docker-slim[build]: info=container status=created name=dockerslimk_1_20191212100526 id=b48f520e260dd7546006394e2bd6ae3196903c557a08482ea734849edea77899
docker-slim[build]: info=cmd.startmonitor status=sent
"docker-slim[build]: info=event.startmonitor.done status=received
docker-slim[build]: info=container name=dockerslimk_1_20191212100526 id=b48f520e260dd7546006394e2bd6ae3196903c557a08482ea734849edea77899 target.port.list=[] target.port.info=[] message='YOU CAN USE THESE PORTS TO INTERACT WITH THE CONTAINER'
docker-slim[build]: state=http.probe.error error='no exposed ports' message='expose your service port with --expose or disable HTTP probing with --http-probe=false if your containerized application doesnt expose any network services
docker-slim[build]: state=exited
```

It exists without errors, but what I see when I run `docker images` is:

```
REPOSITORY                TAG                            IMAGE ID            CREATED             SIZE
docker-slim-empty-image   latest                         31b6562bb3c4        41 seconds ago      0B
my-repo/my-image        latest                         be7aed72c458        20 hours ago        1.27GB
```

Any advice about what I'm doing wrong?

If it helps this are the contents of my `Dockerfile`:
```dockerfile
FROM python:3.6

COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

ENV APP_DIR=/

ADD . ${APP_DIR}

WORKDIR ${APP_DIR}
```

**Comment by kcq** [comment]
What kind of application do you have? What does it do? Is it a server / web service / HTTP API? Does it listen on a port? `docker-slim` exited early because it didn't find an exposed port declared in your Docker image (and your Dockerfile doesn't have an explicit EXPOSE instruction). If your app does listen on a port then you'll need to tell `docker-slim` about that port using the `--expose your_app_port_number` `docker-slim build` flag. If you have command line app and not a server then you need to tell `docker-slim` not to probe your container at runtime. You can do that by passing the `--http-probe=false` `docker-slim build` flag.

**Comment by artdgn** [comment]
Thanks for an even quicker reply! 

After posting the above, I've went into the examples and found as you suggested in your newest comment that I need to specify both `expose` and `cmd` in either `Dockerfile` or the `docker-slim build` command. That did yield a much better result. I was hoping to post here before you could explain that to me and save you the time but you beat me to it :1st_place_medal:  .  

However, my application doesn't really function correctly in the slim version (it's a flask app), it seems that some of the needed files were "slimmed" (it loads though). I'll investigate some more and update.

**Comment by kcq** [comment]
You can try specifying custom http probes to make sure `docker-slim` covers the important endpoints you have in your server app (e.g., `--http-probe-cmd /your/important/endpoint`)

You can find more about the HTTP probes here: https://github.com/docker-slim/docker-slim#http-probe-commands

You can also try enabling the global debug flag to get additional information about what's going on...

**Comment by artdgn** [comment]
I've experimented some more. For whoever might be reading this later:
- I've had some luck with `include-path` by specifying my `/app` dir. 
- However, than some python dependencies were missing (because different endpoints use different python packages), so I've tried specifying multiple include paths in order to protect `/usr/local/lib/python3.6/site-packages/` because that's where python packages live. All the ways I tried including both those paths failed: providing the flag twice (for each path), concatenating the paths into a single string with a separator (`; / : / ,`). Perhaps worth clarifying what this flag can and cannot do in the `--help` command.
- Using `--include-path-file` worked. The subtle complication with using that when running `docker-slim` containerized is that I have to mount that file into the docker-slim container.
- I than ran into other missing dependencies (some in `/usr/lib` , others in `/usr/local/bin`).. The tricky dependency was `scrapy` which is a big scraping package. 

In any case, it seems that including paths is not a very good way (too many false positives and false negatives - so you get large images still and might miss something anyway). 

Probably running an integration test suit when "slimming" would work better. But I don't have that with the toy project I was trying it on. Just hitting the scraping endpoint as part of building is not really an option.

I did find references to most my issues in the documentation eventually, but it seems as though one really has to read most of it to find those details. Probably there's a way to organise the README in a way that would allow a smoother quick-start and would prevent initial pitfalls.

This does seem like a very powerful tool, and I'm pretty sure I'll give it a more serious try with a more serious project (that will require the size reduction) later. Thanks!

**Comment by kcq** [comment]
@artdgn thanks for the extra info! Definitely need to improve and restructure the README file (potentially extending the FAQ section).

Yes, running an integration test suite is something that's useful for some images to ensure better coverage. What do you mean by `Just hitting the scraping endpoint as part of building is not really an option`? Is it because it wouldn't work in the environment where it's built or because it would be too slow or it just something you prefer not to do?

I'm also curious why you were using the containerized version of `docker-slim`.  Is it so you don't need to explicitly download `docker-slim` in your environment?

**Comment by artdgn** [comment]
@kcq The answer is pretty much yes to all your questions:
- Hitting the scraping point can be made to work with additional effort of enabling a way to trigger a very short and light scraping job (which would essentially be equivalent to making an integration test :). Possible but that project doesn't support it at the moment.
- About using containerised version - it feels both simpler and safer (requires less trust) to use a docker image, so that's the option I try first when it is available.
