### ISSUE TITLE
Support podman for building and running

### ISSUE THREAD

**Issue by XVilka** [docker-slim/docker-slim#99]
[Podman](https://podman.io/) is the compatible alternative to docker. Basically changing the direct runs to `docker` bins with the same arguments should work as is.

Something like:
https://github.com/alpinelinux/docker-abuild/commit/8465ec8f46d391fad9e6d994b9af3154bb4ff4ec#diff-a92f8deaded1a4a34523735dc0de7229R35

**Comment by kcq** [comment]
Yes, it'll be good to have support for Podman at some point. Any help there is greatly appreciated ;-)

**Comment by kcq** [comment]
moving this to WISHLIST.md
